### PR TITLE
[backend] Corrected csv formating in feed csv export (#9002)

### LINKED ISSUE #9002: CSV Export Where Description Contains Special Characters Will Not Export Correctly
## Description

When attempting to export data via CSV where the description contains special characters, the CSV export will not work. The response will not be contained on one line. 

## Environment

OpenCTI: 6.3.11

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a CSV Feed with Base Attribute: Creation, Column - Value, Name, and another Column for description. 
2. Create an indicator with a description that contains special characters
3. Once the feed run, open the feed to see the result. 

## Expected Output

The results should all be on a single line. 

## Actual Output

The results are not on one single line. 

## Screenshots (optional)

Image
Image

### PR DESCRIPTION
**Pull request by MTorbay-Filigran**
### Proposed changes

* The csv formating excludes now \r, \n, double quotes, and separator to have a correct csv format.
* The format fonction (buildCsvLines) has been extracted from the initHttpRollingFeeds fonction.

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/9002
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/tests/01-unit/http/httpRollingFeed-test.ts [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
...'description' }], decay_applied_rule: { decay_rule_id: 'dacay-rule-id', decay_lifetime: 470, decay_pound: 0.35, decay_points: [80, 50], decay_revoke_score: 20 }, pattern: 'fezfzefez', description: 'Triggered risk rules:\n\n|Rule|Severity|Score|\n|----|---|----|\n|Ligne 2| colonne 2| colonne 3|\n|Ligne 3| colonne 2| colonne 3|\n\n**test gras**\n\n*test italique*\n~~test barré~~\n\nvirgule\ntest', valid_from: '2025-09-22T13:32:10.875Z', created_at: '2025-09-22T13:32:10.892Z', revoked: false, decay_base_score_date: '2025-09-22T13:32:10.875Z', base_type: 'ENTITY', updated_at: '2025-09-22T13:41:46.875Z', modified: '2025-09-22T13:41:46.875Z', x_opencti_score: 50, lang: 'en', pattern_type: 'shodan', internal_id: 'test-id', created: '2025-09-22T13:32:10.892Z', confidence: 100, x_opencti_main_observable_type: 'Cryptocurrency-Wallet', x_mitre_platforms: [], decay_next_reaction_date: '2026-06-24T10:51:42.710Z', valid_until: '2026-06-24T10:51:42.710Z', entity_type: 'Indicator', indicator_types: [], name: 'test csv encore', creator_id: ['user-id'], x_opencti_detection: false, decay_base_score: 50, x_opencti_stix_ids: [], decay_history: [{ updated_at: '2025-09-22T13:32:10.875Z', score: 50 }] }];
```
Comment (esrevi) [inline opencti-platform/opencti-graphql/tests/01-unit/http/httpRollingFeed-test.ts]: maybe we could create a function such as (with the values you already have)
```
const createMockElement = (overrides: Partial<any> = {}) => ({
  _index: 'opencti_stix_domain_objects-000001',
  _id: 'test-id',
  id: 'test-id',
  sort: [1758547930892, 'test-id', 'indicator--id'],
  standard_id: 'indicator--id',
  parent_types: ['Basic-Object', 'Stix-Object', 'Stix-Core-Object', 'Stix-Domain-Object'],
  i_attributes: [{
    updated_at: '2025-09-22T13:41:46.875Z',
    user_id: 'user-id',
    confidence: 100,
    name: 'description'
  }],
  decay_applied_rule: {
    decay_rule_id: 'dacay-rule-id',
    decay_lifetime: 470,
    decay_pound: 0.35,
    decay_points: [80, 50],
    decay_revoke_score: 20
  },
  pattern: 'fezfzefez',
  description: 'Triggered risk rules:\n\n|Rule|Severity|Score|\n|----|---|----|\n|Ligne 2| colonne 2| colonne 3|\n|Ligne 3| colonne 2| colonne 3|\n\n**test gras**\n\n*test italique*\n~~test barré~~\n\nvirgule\ntest',
  valid_from: '2025-09-22T13:32:10.875Z',
  created_at: '2025-09-22T13:32:10.892Z',
  revoked: false,
  decay_base_score_date: '2025-09-22T13:32:10.875Z',
  base_type: 'ENTITY',
  updated_at: '2025-09-22T13:41:46.875Z',
  modified: '2025-09-22T13:41:46.875Z',
  x_opencti_score: 50,
  lang: 'en',
  pattern_type: 'shodan',
  internal_id: 'test-id',
  created: '2025-09-22T13:32:10.892Z',
  confidence: 100,
  x_opencti_main_observable_type: 'Cryptocurrency-Wallet',
  x_mitre_platforms: [],
  decay_next_reaction_date: '2026-06-24T10:51:42.710Z',
  valid_until: '2026-06-24T10:51:42.710Z',
  entity_type: 'Indicator',
  indicator_types: [],
  name: 'test csv encore',
  creator_id: ['user-id'],
  x_opencti_detection: false,
  decay_base_score: 50,
  x_opencti_stix_ids: [],
  decay_history: [{ updated_at: '2025-09-22T13:32:10.875Z', score: 50 }],
  ...overrides
});
```

Thus, in the test, it could be easier to maintain and to evolve with, by overriding the fields you need to test
```
  const descriptionWithIssues = 'Triggered risk rules:\n\n|Rule|Severity;|Score|\n|----|---|----|\n|Ligne 2| colonne" 2| colonne 3|\n|Ligne 3| colonne 2| colonne 3|\n\n**test \rgras**\n\n*test italique*\n~~test barré~~\n\nvirgule\ntest';
  const elements = [createMockElement({ description: descriptionWithIssues })];
```

File: opencti-platform/opencti-graphql/tests/01-unit/http/httpRollingFeed-test.ts [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
...cription' }], decay_applied_rule: { decay_rule_id: 'dacay-rule-id', decay_lifetime: 470, decay_pound: 0.35, decay_points: [80, 50], decay_revoke_score: 20 }, pattern: 'fezfzefez', description: 'Triggered risk rules:\n\n|Rule|Severity;|Score|\n|----|---|----|\n|Ligne 2| colonne" 2| colonne 3|\n|Ligne 3| colonne 2| colonne 3|\n\n**test \rgras**\n\n*test italique*\n~~test barré~~\n\nvirgule\ntest', valid_from: '2025-09-22T13:32:10.875Z', created_at: '2025-09-22T13:32:10.892Z', revoked: false, decay_base_score_date: '2025-09-22T13:32:10.875Z', base_type: 'ENTITY', updated_at: '2025-09-22T13:41:46.875Z', modified: '2025-09-22T13:41:46.875Z', x_opencti_score: 50, lang: 'en', pattern_type: 'shodan', internal_id: 'test-id', created: '2025-09-22T13:32:10.892Z', confidence: 100, x_opencti_main_observable_type: 'Cryptocurrency-Wallet', x_mitre_platforms: [], decay_next_reaction_date: '2026-06-24T10:51:42.710Z', valid_until: '2026-06-24T10:51:42.710Z', entity_type: 'Indicator', indicator_types: [], name: 'test csv encore', creator_id: ['user-id'], x_opencti_detection: false, decay_base_score: 50, x_opencti_stix_ids: [], decay_history: [{ updated_at: '2025-09-22T13:32:10.875Z', score: 50 }] }];
```
Comment (esrevi) [inline opencti-platform/opencti-graphql/tests/01-unit/http/httpRollingFeed-test.ts]: then we can remove  elementsWithCaractersToRemove

File: opencti-platform/opencti-graphql/tests/01-unit/http/httpRollingFeed-test.ts [hunk 3]
```diff
@@ -0,0 +1,86 @@
...
+
+describe('buildCsvLines', () => {
+  it('should convert elements to CSV lines and remove carriage return', () => {
+    const expectedResultLines: string[] = [
+      '"test csv encore";"Triggered risk rules:  |Rule|Severity|Score| |----|---|----| |Ligne 2| colonne 2| colonne 3| |Ligne 3| colonne 2| colonne 3|  **test gras**  *test italique* ~~test barré~~  virgule test"',
+    ];
+    const resultLines = buildCsvLines(elements, feed);
```
Comment (esrevi) [inline opencti-platform/opencti-graphql/tests/01-unit/http/httpRollingFeed-test.ts:84]: here, we could do: 
```
const descriptionWithIssue = 'Triggered risk rules:\n\n|Rule|Severity;|Score|\n|----|---|----|\n|Ligne 2| colonne" 2| colonne 3|\n|Ligne 3| colonne 2| colonne 3|\n\n**test \rgras**\n\n*test italique*\n~~test barré~~\n\nvirgule\ntest';
      
const elements = [createMockElement({ description: descriptionWithIssue })];
      
const resultLines = buildCsvLines(elements, mockFeed);
```

Then, i think it is more obvious to understand what we want to assert

**Review by esrevi — APPROVED** [review]
lgtm, the csv seems in good shape now but maybe wait for another approval of someone who knows better the feature because I don't know if it is the expected output we want :)

**Comment by maelv-filigran** [comment]
##  Data Loss Issue

Good job extracting the logic and adding tests, but there's a critical issue.

### The Problem

Line 34: `data.replaceAll('"', '').replaceAll(separator, '').replaceAll('\n', ' ')`

This **removes** characters instead of handling them per CSV standards. Users lose data.

What happens when a user's description contains: `"Critical security issue: check the "admin" panel"`?

- Current output: `Critical security issue: check the admin panel`
- User's data is permanently altered

### Key Questions

1. **Have you checked RFC 4180?** 
   - CSV has a standard way to escape quotes: double them (`""`)
   - Newlines are allowed inside quoted fields

2. **Why delete instead of escape?**
   - CSV is about formatting, not sanitizing
   - What happens when users need those characters?

3. **Do all fields need quotes?**
   - Currently you quote everything
   - Only special cases need quotes

### Quick Fix Direction

Research how CSV libraries handle this:
- Quotes: `"` → `""`  (not delete)
- Fields with special chars: wrap in quotes
- Keep newlines inside quoted fields

Your test expects quotes to disappear - that's the bug, not the feature.


The structure is good, just need to fix the escaping logic. Let me know if you need pointers on CSV standards.

**Review by maelv-filigran — APPROVED** [review]
