### PR TITLE
[backend] prevent score loop change on sources conflict and fix upsert of revoke (#11986)

### LINKED ISSUE #11986: Indicator decay history filling with back and forth revoke and score update
## Description

We have multiple cases (in testing & prod) where indicators have a large decay history and updates of revoke (along with score in some cases)

Image

Image

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 } latest (6.7.10)
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

### PR DESCRIPTION
**Pull request by aHenryJard**
### Proposed changes

* Add the user id in decay_history
* prevent same user_id to update or upsert the same score - only when decay is enabled
  * add a new field 'updated_by'
  * split in to object: data point to draw curve on screen (DecayHistoryChart), DecayHistory is for storage
* fix the upsert on unrevoking indicator that has been forgotten in previous fix (https://github.com/OpenCTI-Platform/opencti/issues/10299)
* update documentation https://github.com/OpenCTI-Platform/docs/pull/280

### Related issues

* closes #11986 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case (coverage and e2e)
- [x] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/database/middleware.js [hunk 1]
```diff
@@ -2725,25 +2726,39 @@ const upsertElement = async (context, user, element, type, basePatch, opts = {})
...
-      // updatePatch.decay_base_score = element.decay_base_score; // no need since it's the same score
-      updatePatch.revoked = resolvedElement.revoked;
-      updatePatch.decay_base_score_date = resolvedElement.decay_base_score_date;
-      updatePatch.decay_applied_rule = resolvedElement.decay_applied_rule;
-      updatePatch.decay_history = []; // History is multiple, forcing to empty array will prevent any modification
-      updatePatch.decay_next_reaction_date = resolvedElement.decay_next_reaction_date;
-    } else {
-      // As base_score as change, decay will be reset by upsert
-      logApp.debug('UPSERT INDICATOR -- Decay is reset', { resolvedElement, basePatch });
+    if (updatePatch.decay_applied_rule) {
```
Comment (JeremyCloarec) [inline opencti-platform/opencti-graphql/src/database/middleware.js]: I don't fully understand why the if condition was split in two. Was it intended that we no longer go into the else condition
```
// As base_score as change, decay will be reset by upsert
logApp.debug('UPSERT INDICATOR -- Decay is restarted', { resolvedElement, basePatch })
```
if updatePatch doesn't contain a decay_applied_rule?

**Review by JeremyCloarec — DISMISSED** [review]

File: opencti-platform/opencti-graphql/src/database/middleware.js [hunk 2]
```diff
@@ -2864,9 +2880,11 @@ const upsertElement = async (context, user, element, type, basePatch, opts = {})
   if (inputs.length > 0) {
     // Update the attribute and return the result
     const updateOpts = { ...opts, upsert: context.synchronizedUpsert !== true };
+    logApp.info('UPSERT - END', { inputs, updateOpts, resolvedElement });
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/database/middleware.js]: to be removed

File: opencti-platform/opencti-graphql/src/database/middleware.js [hunk 3]
```diff
@@ -2864,9 +2880,11 @@ const upsertElement = async (context, user, element, type, basePatch, opts = {})
...
     return await updateAttributeMetaResolved(context, user, resolvedElement, inputs, updateOpts);
   }
   // -- No modification applied
+  logApp.info('UPSERT - End No modification applied');
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/database/middleware.js]: to be removed

File: opencti-platform/opencti-graphql/tests/02-integration/01-database/indicator-domain-test.ts [hunk 4]
```diff
@@ -220,33 +230,221 @@ describe('Testing field patch on indicator for trio {score, valid until, revoked
...
+      x_opencti_score: 80,
+      valid_from: inPast90Days,
+      valid_until: inFiveDays,
+    };
+    await createIndicator(ADMIN_USER, indicatorUpsert2);
+    const indicatorAfterUpsert2 = await findById(testContext, ADMIN_USER, indicatorCreated.id);
+    expect(indicatorAfterUpsert2.x_opencti_score).toBe(75); // score update is ignored
+  });
+
+  it.todo('should upsert 2 times with same source and same score be ignored - without decay', async () => {
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/tests/02-integration/01-database/indicator-domain-test.ts]: need to make that work

File: opencti-platform/opencti-graphql/src/database/middleware.js [hunk 5]
```diff
@@ -2760,25 +2761,40 @@ const upsertElement = async (context, user, element, type, basePatch, opts = {})
...
+        // don't reset decay attributes
+        // updatePatch.decay_base_score = element.decay_base_score; // no need since it's the same score
+        updatePatch.revoked = resolvedElement.revoked;
+        updatePatch.decay_base_score_date = resolvedElement.decay_base_score_date;
+        updatePatch.decay_applied_rule = resolvedElement.decay_applied_rule;
+        updatePatch.decay_history = []; // History is multiple, forcing to empty array will prevent any modification
+        updatePatch.decay_next_reaction_date = resolvedElement.decay_next_reaction_date;
+      } else {
+        // As base_score as change, decay will be reset by upsert
+        logApp.info('UPSERT INDICATOR -- Decay is restarted', { resolvedElement, basePatch });
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/database/middleware.js]:
```suggestion
        logApp.debug('UPSERT INDICATOR -- Decay is restarted', { resolvedElement, basePatch });
```

File: opencti-platform/opencti-graphql/src/database/middleware.js [hunk 6]
```diff
@@ -2760,25 +2761,40 @@ const upsertElement = async (context, user, element, type, basePatch, opts = {})
...
-      // As base_score as change, decay will be reset by upsert
-      logApp.debug('UPSERT INDICATOR -- Decay is reset', { resolvedElement, basePatch });
+    logApp.info('UPSERT INDICATOR - ****', { userId: user.id, score: updatePatch.x_opencti_score, history: resolvedElement.decay_history, updatePatchHistory: updatePatch.decay_history });
+    if (updatePatch.decay_applied_rule) {
+      const isScoreInUpsertSameAsBaseScore = updatePatch.decay_base_score === resolvedElement.decay_base_score && updatePatch.decay_base_score === resolvedElement.x_opencti_score;
+      // Do not compute decay again when base score does not change
+      // or when the same score update has already been done
+      if ((!resolvedElement.revoked && isScoreInUpsertSameAsBaseScore)
+          || (hasSameSourceAlreadyUpdateThisScore(user.id, updatePatch.x_opencti_score, resolvedElement.decay_history))) {
+        logApp.info(`UPSERT INDICATOR -- SKIP DECAY, do not change score, keep:${resolvedElement.x_opencti_score}`);
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/database/middleware.js]:
```suggestion
        logApp.debug(`UPSERT INDICATOR -- SKIP DECAY, do not change score, keep:${resolvedElement.x_opencti_score}`);
```

File: opencti-platform/opencti-graphql/src/database/middleware.js (hunk 1 above)
Comment (aHenryJard) [reply opencti-platform/opencti-graphql/src/database/middleware.js]: if there is no decay rule, it means that decay is not applied to current indicator, there is nothing to do

File: opencti-platform/opencti-graphql/src/manager/publisherManager.ts [hunk 7]
```diff
@@ -229,7 +229,7 @@ export async function handleWebhookNotification(configurationString: string | un
   try {
     await httpClient.call({ url, method: verb, params: paramsObject, data: webhookPayload });
   } catch (error) {
-    logApp.error('[OPENCTI-MODULE] Publisher manager webhook error', { cause: error, manager: 'PUBLISHER_MANAGER' });
+    logApp.error('[OPENCTI-MODULE] Publisher manager webhook error', { cause: error, manager: 'PUBLISHER_MANAGER', url });
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/manager/publisherManager.ts:235]: this is not related to PR changes, but it's a pain on production log to find the webhook raising this error.

**Review by marieflorescontact — COMMENTED** [review]
locally  tested ok 🙂

**Review by marieflorescontact — APPROVED** [review]
