### PR TITLE
[FRONTEND] Corrected diamond display of attributed campains in threats (#11580)

### LINKED ISSUE #11580: No updates in last attributions of Diamond Model
## Description
Using the attached list of possibilities for the Diamond model views, I am unable to see the last attributions updated in the adversary view.

## Environment
SaaS 6.7.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Starting with the 'entity type' column from the Excel sheet as the source for the diamond model, in this case, we can use  threat actor group
2. Select a threat actor and then Knowledge tab
3. On the Adversary, click 'View all'
4. Click the plus and add Campaign attributed to TA (first entry from the spreadsheet)
5. Click back to the knowledge tab, no last attribution have been updated.

## Expected Output
Last attributions to have been updated

## Actual Output
Nothing shown

## Additional information

At this point I am not sure if the provided data on the DM is incorrect / needs adjusting or it has not been added to the platform. If correct in the platform then a guide showing what is allowed / possible.

[Diamond Model Views.xlsx](https://github.com/user-attachments/files/21031282/Diamond.Model.Views.xlsx)

### PR DESCRIPTION
**Pull request by MTorbay-Filigran**
### Proposed changes

* I completed the graphQL query so that we can get the attributedFrom relationships in order to display attributed campaigns in diamond of threats (Threat Actors, group and individual, and Intrusion sets)
* I changed the nodeAdversary to integrate that case (it is not an attributed to like for other cases but an attributed from in case of threats)
* I moved the nodeAdversary logic in a hook to be able to add UT
* I renamed the enums of diamond from type to enum and moved them into a separate folder

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/11580
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeAdversary/useNodeAdversary.ts [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+}
+export interface UseNodeAdversaryReturns {
+  entityLink: string;
+  generatedFilters: string;
+  aliases?: string;
+  isArsenal: boolean;
+  lastAttributions: React.ReactNode;
+}
+
+export const useNodeAdversary = ({ data }: UseNodeAdversaryProps):UseNodeAdversaryReturns => {
```
Comment (Archidoit) [inline opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeAdversary/useNodeAdversary.ts]: it's useless to create a hook in this case... We can just create a utils function :)

Comment (Archidoit) [reply opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeAdversary/useNodeAdversary.ts]: In your case, you just wanted to separate the logic to test it unitarily, and you don't use any hook inside useNodeAdversary. So the logic can be put in a classic utils function

File: opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeAdversary/nodeAdversaryUtils.ts [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+
+export const useNodeAdversary = ({ data }: UseNodeAdversaryProps):UseNodeAdversaryReturns => {
+  const { stixDomainObject, entityLink } = data;
+
+  const isArsenal = [DiamondEntityEnum.malware, DiamondEntityEnum.tool, DiamondEntityEnum.channel].includes(stixDomainObject.entity_type);
+  const isThreat = [DiamondEntityEnum.threatActorGroup, DiamondEntityEnum.threatActorIndividual, DiamondEntityEnum.intrusionSet].includes(stixDomainObject.entity_type);
+
+  const aliases = stixDomainObject.aliases?.slice(0, 5).join(', ');
+
+  const attributedTo = R.uniq((stixDomainObject.attributedTo?.edges ?? [])
```
Comment (Archidoit) [inline opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeAdversary/nodeAdversaryUtils.ts:42]: why a uniq in this case? :)

**Comment by Archidoit** [comment]
Behavior ok, working well :)

File: opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeAdversary/nodeAdversaryUtils.ts (hunk 2 above)
Comment (MTorbay-Filigran) [reply opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeAdversary/nodeAdversaryUtils.ts:42]: I used the same logic that was already there, as I understood to avoid duplicates.

File: opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeAdversary/nodeAdversaryUtils.test.ts [hunk 3]
```diff
@@ -0,0 +1,81 @@
+import { afterEach, describe, expect, it, vi } from 'vitest';
+import * as getFilterFromEntityTypeAndNodeType from '@components/common/stix_domain_objects/diamond/getFilterFromEntityTypeAndNodeType';
+import { nodeAdversaryUtils, UseNodeAdversaryProps } from './nodeAdversaryUtils';
+
+import { DiamondEntityEnum } from '../diamondEnums';
+
+describe('useNodeAdversary', () => {
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeAdversary/nodeAdversaryUtils.test.ts]: Need to realigned with new utils name

File: opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeAdversary/nodeAdversaryUtils.ts [hunk 4]
```diff
@@ -0,0 +1,88 @@
+import * as R from 'ramda';
+import getFilterFromEntityTypeAndNodeType from '@components/common/stix_domain_objects/diamond/getFilterFromEntityTypeAndNodeType';
+import { emptyFilled } from '../../../../../../../../utils/String';
+import { DiamondEntityEnum, DiamondNodeEnum } from '../diamondEnums';
+
+export interface UseNodeAdversaryProps {
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeAdversary/nodeAdversaryUtils.ts]: Should be renamed with new name

File: opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeAdversary/nodeAdversaryUtils.ts [hunk 5]
```diff
@@ -0,0 +1,88 @@
...
+              name: string;
+            };
+          };
+        }[];
+      };
+    };
+    entityLink: string;
+  };
+}
+export interface UseNodeAdversaryReturns {
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeAdversary/nodeAdversaryUtils.ts]: renaming

File: opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeAdversary/nodeAdversaryUtils.ts (hunk 4 above)
Comment (lndrtrbn) [reply opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeAdversary/nodeAdversaryUtils.ts]: I think we should avoid defining complex types when we can use Relay generated types, can we do this here?

File: opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectDiamond.jsx [hunk 6]
```diff
@@ -553,6 +553,29 @@ const StixDomainObjectDiamond = createRefetchContainer(
           ... on IntrusionSet {
             name
             aliases
+            attributedFrom: stixCoreRelationships(
+              relationship_type: "attributed-to"
+              fromTypes: ["Campaign"]
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectDiamond.jsx:558]: Is it on purpose to set hard coded `Campaign` here? No other values possible?

File: opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectDiamond.jsx [hunk 7]
```diff
@@ -553,6 +553,29 @@ const StixDomainObjectDiamond = createRefetchContainer(
...
+                  from {
+                    ... on ThreatActor {
+                      name
+                    }
+                    ... on IntrusionSet {
+                      name
+                    }
+                    ... on Campaign {
+                      name
+                    }
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectDiamond.jsx:580]: I think you can use
```
representative {
  main
}
```
that is present for all types, instead of defining name for each case

File: opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectDiamond.jsx (hunk 6 above)
Comment (MTorbay-Filigran) [reply opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectDiamond.jsx:558]: It is the only purpose of the issue, so I did not put more cases

File: opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeAdversary/nodeAdversaryUtils.ts [hunk 8]
```diff
@@ -0,0 +1,82 @@
...
+  attributedFrom?: {
+    edges: {
+      node: {
+        from: {
+          name?: string;
+        } | null | undefined;
+      };
+    }[];
+  } | null | undefined;
+} | null | undefined;
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeAdversary/nodeAdversaryUtils.ts]: You do not need all this. 
`StixDomainObjectDiamond_data$data['stixDomainObject']` is sufficient

**Review by lndrtrbn — APPROVED** [review]
