### PR TITLE
[frontend] In the data tab, fix opening the file in a new window (#14254)

### LINKED ISSUE #14254: In the data tab, ctrl+click on files is not working
## Description

In the data tab, ctrl+click on files is not working
Image

Try to ctrl+click to see json or text files, it will open in the same window

### PR DESCRIPTION
**Pull request by CelineSebe**
### Proposed changes

* fix opening the file in a new window in the data tab

### Related issues

* resolved #14254

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/common/files/ImportActionsPopover.tsx [hunk 1]
```diff
@@ -100,9 +100,15 @@ const ImportActionsPopover = ({
...
+          onClick={(event: React.MouseEvent) => {
             stopEvent(event);
-            window.location.pathname = `${APP_BASE_PATH}/storage/get/${encodeURIComponent(file.id)}`;
+            setAnchorEl(null);
+            const url = `${APP_BASE_PATH}/storage/get/${encodeURIComponent(file.id)}`;
+            if (event.ctrlKey || event.metaKey) {
+              window.open(url, '_blank', 'noopener,noreferrer');
+            } else {
+              window.location.pathname = url;
+            }
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/private/components/common/files/ImportActionsPopover.tsx]: I think the changes here are not necessary. You don't need any custom behavior to download the file, it won't open the file in the current tab anyway

**Review by lndrtrbn — CHANGES_REQUESTED** [review]
In the issue, it has been ask by Nino to always open the file in a new tab, no matter the ctrl button is pressed or not

File: opencti-platform/opencti-front/src/private/components/common/files/FileLine.tsx [hunk 2]
```diff
@@ -226,11 +226,15 @@ const FileLineComponent: FunctionComponent<FileLineComponentProps> = ({
     }
   };
 
-  const handleLink = (url: string) => {
+  const handleLink = (url: string, event?: React.MouseEvent) => {
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/private/components/common/files/FileLine.tsx]: As you are not using the event in the function, prefer using a variable that describe the purpose, for example a boolean called `inNewWindow`

File: opencti-platform/opencti-front/src/schema/relay.schema.graphql [hunk 3]
```diff
@@ -2234,7 +2234,7 @@ type ManagerContractConfiguration {
 type ManagerContractExcerpt {
   title: String!
   slug: String!
-  logo: String!
+  logo: String
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/schema/relay.schema.graphql]: This change does not seem related to the bug, what is it for?

**Review by lndrtrbn — APPROVED** [review]
