### PR TITLE
[backend] fix endless spinning for Csv import connector (#12196)

### LINKED ISSUE #12196: Draft: incorrect tracking numbers lead to endless spinning in UI
## Description

More operations than entities in a draft cause endless spinning in draft, giving the feeling that import is never finished. 

## Environment

Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Import in draImport a large file (10K+ email) csv
2. Import in a draft
3.See that the draft never finishes.

### PR DESCRIPTION
**Pull request by CelineSebe**
### Proposed changes

* fix number of operations

### Related issues

* #12196 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/connector/importCsv/importCsv-connector.ts [hunk 1]
```diff
@@ -90,7 +90,6 @@ export const processCSVforWorkers = async (context: AuthContext, fileId: string,
     const stream: SdkStream<Readable> | null | undefined = await downloadFile(fileId) as SdkStream<Readable> | null | undefined;
     if (stream) {
       // start UI count, import of file = 1 operation.
```
Comment (JeremyCloarec) [inline opencti-platform/opencti-graphql/src/connector/importCsv/importCsv-connector.ts]: You can remove this comment line also since it's no longer relevant :)

**Review by JeremyCloarec — APPROVED** [review]
