### PR TITLE
[backend] fix creator batch loading (#14307)

### LINKED ISSUE #14307: Crash on Individuals page
## Description

There is a crash on the Entities > Individuals page because of a TS error when no user : 
Image

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

### PR DESCRIPTION
**Pull request by Archidoit**
### Proposed changes
Fix creator batch loading

### Related issues
#14307

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/database/members.ts [hunk 1]
```diff
@@ -20,10 +21,14 @@ export const loadCreator = async (
   context: AuthContext,
   user: AuthUser,
   userIdToLoad?: string,
-) => {
-  if (!userIdToLoad) return null;
+): Promise<Creator> => {
   const realUser = await context.batch?.creatorBatchLoader.load(userIdToLoad);
-  if (!realUser) return null;
+  if (!realUser) {
```
Comment (MTorbay-Filigran) [inline opencti-platform/opencti-graphql/src/database/members.ts:26]: If you don't have a type error on this one, couldn't it be possible to return the same before calling creatorBatchLoader.load if userIdToLoad is undefined ?

**Review by MTorbay-Filigran — APPROVED** [review]
