### PR TITLE
[frontend] fix: prevent using relay cache when checking connectivity (#15516)

### LINKED ISSUE #15516: The button of unregister/register in the OCTI is not updated accordingly
## Description

Refers to https://github.com/FiligranHQ/xtm-hub/issues/2112

### PR DESCRIPTION
**Pull request by Kroustille**
### Proposed changes

* add network only to relay to prevent using cached data

### Related issues

* Fixes #15516
* Refers to https://github.com/FiligranHQ/xtm-hub/issues/2112

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

https://github.com/user-attachments/assets/3c5ccb83-17d5-4503-9f48-e13d492a759b

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/settings/xtm-hub/XtmHubSettings.tsx [hunk 1]
```diff
@@ -40,6 +40,7 @@ const XtmHubSettingsComponent = () => {
   const { settings: xtmHubSettings } = useLazyLoadQuery<XtmHubSettingsQuery>(
     xtmHubSettingsQuery,
     {},
+    { fetchPolicy: 'network-only' },
```
Comment (jpkha) [inline opencti-platform/opencti-front/src/private/components/settings/xtm-hub/XtmHubSettings.tsx:43]: It’s quite strange that changing the fetchPolicy fixes the issue, since the request is actually being sent and returns the correct response.

That said, the solution works for me because we mainly need the correct data during loading.

**Review by jpkha — APPROVED** [review]

**Review by aHenryJard — APPROVED** [review]
