### PR TITLE
[backend] avoid Maximum call stack size exceeded in resolveMissingReferences (#12923)

### LINKED ISSUE #12923: LiveStream stuck with ""code":"UNKNOWN_ERROR","message":"Maximum call stack size exceeded"
## Description

We have a custom process that consumes from OpenCTI's Livestream. Recently the consumer got stuck. Within our platform, we see the log:

```
"category":"APP","cause":{"code":"UNKNOWN_ERROR","message":"Maximum call stack size exceeded","name":"RangeError","stack":"RangeError: Maximum call stack size exceeded\n    at resolveMissingReferences (/opt/app-root/src/opencti-platform-build/opencti/build/back.js:3900:121434)\n    at runNextTicks (node:internal/process/task_queues:60:5)\n    at process.processImmediate (node:internal/timers:454:9)\n    at async resolveAndPublishMissingRefs (/opt/app-root/src/opencti-platform-build/opencti/build/back.js:3904:2194)\n    at async resolveAndPublishDependencies (/opt/app-root/src/opencti-platform-build/opencti/build/back.js:3904:3423)\n    at async createStreamProcessor.autoReconnect (/opt/app-root/src/opencti-platform-build/opencti/build/back.js:3904:10308)\n    at async processStreamResult (/opt/app-root/src/opencti-platform-build/opencti/build/back.js:1904:9044)\n    at async processStep (/opt/app-root/src/opencti-platform-build/opencti/build/back.js:1904:9625)\n    at async processingLoop (/opt/app-root/src/opencti-platform-build/opencti/build/back.js:1904:9971)\n    at async Object.shutdown (/opt/app-root/src/opencti-platform-build/opencti/build/back.js:1904:10533)"},"level":"error","message":"Redis stream consume fail","provider":"connector-stream-export@email.com","source":"backend","timestamp":"2025-10-23T15:22:44.009Z","version":"6.6.18"}
```

The consumer is stuck at the Redis Stream ID: 1761072424763-0.

Using redis-cli XREAD COUNT 1 STREAMS stream.opencti 1761072424763-0 I can see that the following event (what the stream is trying to serve) is:

```
stream.opencti
1761072428960-0
version
"4"
type
"update"
scope
"external"
message
"adds `boeing-careers.com, boeing-careers.com, boeing-careers.com ➡️ boeing-careers.com` in `Contains` and 1245 more items"
origin
{"socket":"query","ip":"::1","user_id":"UUID_OF_ALIENVAULT_CONNECTOR","group_ids":["UUID","UUID"],"organization_ids":[],"user_metadata":{},"applicant_id":"UUID","call_retry_number":"0"}
data
VERY_LARGE_JSON (~6.2MB)
context
LARGE_JSON
```

This AlienVault (Infrastructure of Interest: Medium Confidence Detection) report relates to 43.34K entities.

I can see that the stream does produce A LOT of dependencies, my assumption is that this is to ensure stream events are self-contained. I assume this event refers to too many dependencies.

## Environment

1. OS UBI9 Python3.9
2. OpenCTI version: 6.6.18
3. OpenCTI client: Error occurs on our ingest/backend platform. We have a custom consumer of the LiveStream, which just uses the pycti "ListenStream" function (https://github.com/OpenCTI-Platform/client-python/blob/6.6.18/pycti/connector/opencti_connector_helper.py#L660)
4. Other environment details: 
	- OpenSearch v3.2
	- Redis HA v7.4.6

## Reproducible Steps

Steps to create the smallest reproducible scenario:
- Quite hard to fully reproduce, as I believe this may be related to the large amount of interlinked data on our platform.

## Expected Output

The stream is able to continue despite this event.

## Actual Output

The stream consumer is paused and stuck on 1761072424763-0, eventually receiving the above error in the platform

## Additional information

Happy to provide more information / try stuff on my end.

We do have a very large platform:
- 7 Million Indicators
- 15 Million Relationships

### PR DESCRIPTION
**Pull request by xfournet**
### Proposed changes

* Do not spread elements of large arrays when building the missingElements array

### Related issues
* Fix #12923 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js [hunk 1]
```diff
@@ -205,13 +205,13 @@ const createSseMiddleware = () => {
     const missingElements = [];
     if (refsToResolve.length > 0) {
       const resolvedStoreElements = await storeLoadByIdsWithRefs(context, user, refsToResolve);
-      missingElements.push(...resolvedStoreElements);
+      largeArrayPush(missingElements, resolvedStoreElements);
```
Comment (JeremyCloarec) [inline opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js]: Here missingElements hasn't been modified yet, can't we just make missingElements mutable and assign resolvedStoreElements to it instead of doing the largeArrayPush operation?

File: opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js [hunk 2]
```diff
@@ -205,13 +205,13 @@ const createSseMiddleware = () => {
...
       const resolvedMissingIds = await asyncMap(missingElements, (elem) => extractIdsFromStoreObject(elem), undefined, { flat: true });
       const allRefs = await uniqAsyncMap(resolvedStoreElements, (r) => stixRefsExtractor(convertStoreToStix(r)), undefined, { flat: true });
       const parentRefs = await asyncFilter(allRefs, (parentId) => !resolvedMissingIds.includes(parentId));
       if (parentRefs.length > 0) {
         const newMissing = await resolveMissingReferences(context, user, parentRefs, cache);
-        missingElements.unshift(...newMissing);
+        largeArrayUnshift(missingElements, newMissing);
```
Comment (JeremyCloarec) [inline opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js]: Can't we rely on JS array concat method instead of implementing our own?
`missingElements = newMissing.concat(missingElements)`

Comment (xfournet) [reply opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js]: We could, but it's a bit different, concat is creating a new array. That said i didn't test if there is performance difference between the two approach

File: opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js (hunk 1 above)
Comment (xfournet) [reply opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js]: Good catch, i have removed the utils, and reworked the method

File: opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js (hunk 2 above)
Comment (xfournet) [reply opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js]: i removed the util

File: opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js [hunk 3]
```diff
@@ -200,22 +200,37 @@ const createSseMiddleware = () => {
...
+    }
+
+    const allRefs = await uniqAsyncMap(missingElements, (r) => stixRefsExtractor(convertStoreToStix(r)), undefined, { flat: true });
+    if (allRefs.length === 0) {
+      return missingElements;
     }
-    return missingElements;
+
+    const resolvedMissingIds = new Set(await asyncMap(missingElements, (elem) => extractIdsFromStoreObject(elem), undefined, { flat: true }));
+    const parentRefs = allRefs.filter((parentId) => !resolvedMissingIds.has(parentId));
```
Comment (xfournet) [inline opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js:221]: I build a Set to avoid the array includes. The filter should now be fast enough to avoid event loop blocking (1 millions search in less than 50 ms)

**Review by JeremyCloarec — APPROVED** [review]
