### PR TITLE
[backend] fix buggy history events (#14537)

### LINKED ISSUE #14537: Error on history event processing on [noHistory] forbidden in context_data.changes
## Description

In 20ddd3772144d29d8ea74b9b60ff9ce0540be753 the storeUpdateEvent signature has been updated, but some callers remains unchanged. This was fix in 1c1a0b66749269c0e6785223d46c601d4577fbe8

In meantime (in release 6.8.16 , 6.8.17 and 6.9.0), events may have been generated with changes = the option array instead of an empty change array.

This lead to this kind of errors:

```
{"category":"APP","cause":{"attributes":{"errors":[{"reason":"[1:993] mapping set to strict, dynamic introduction of [noHistory] within [context_data.changes] is not allowed","type":"strict_dynamic_mapping_exception"}],"genre":"TECHNICAL","http_status":500},"code":"DATABASE_ERROR","message":"Bulk indexing fail","name":"DATABASE_ERROR","stack":"GraphQLError: Bulk indexing fail\n    at error (/opt/opencti/build/back.js:559713:10)\n    at DatabaseError (/opt/opencti/build/back.js:559769:40)\n    at /opt/opencti/build/back.js:579263:15\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async elIndexElementsFn (/opt/opencti/build/back.js:579854:9)\n    at async eventsApplyHandler (/opt/opencti/build/back.js:712459:3)\n    at async historyStreamHandler (/opt/opencti/build/back.js:712474:7)\n    at async processStreamResult (/opt/opencti/build/back.js:580649:3)\n    at async processStep (/opt/opencti/build/back.js:580688:31)\n    at async processingLoop (/opt/opencti/build/back.js:580709:12)\n    at async /opt/opencti/build/back.js:580729:13"},"level":"error","manager":"HISTORY_MANAGER","message":"[OPENCTI-MODULE] History manager stream error","source":"backend","timestamp":"2026-02-18T17:40:08.498Z","version":"6.9.20"}
```

### PR DESCRIPTION
**Pull request by xfournet**
### Proposed changes

* Ignore non-array update events changes, replace by an empty array

### Related issues
* Fix #14537 

### Checklist

- [x] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/manager/historyManager.ts [hunk 1]
```diff
@@ -183,8 +183,8 @@ export const buildHistoryElementsFromEvents = async (context: AuthContext, event
         const relatedMarkings = updateEvent.context.related_restrictions.markings ?? [];
         pushAll(eventMarkingRefs, relatedMarkings);
       }
-      // add changes
-      contextData.changes = updateEvent.context.changes;
+      // See GitHub issue #14537, we need to discard invalid changes events that have been generated in buggy OpenCTI versions (6.8.16, 6.8.17 and 6.9.0)
+      contextData.changes = Array.isArray(updateEvent.context.changes) ? updateEvent.context.changes : [];
```
Comment (fellowseb) [inline opencti-platform/opencti-graphql/src/manager/historyManager.ts:187]: Would it be useful logging a warn saying we detected corrupted data, in the non-array case ?

File: opencti-platform/opencti-graphql/src/manager/historyManager.ts
Comment (fellowseb) [inline opencti-platform/opencti-graphql/src/manager/historyManager.ts:151]: (thinking out loud, no action required. Related to the original bug)

We could consider using `yup` / `zod` schemas and activating runtime validation in dev mode and tests at least to see such issues sooner. (Of course, migrating to TS, like middleware.ts in this case, helps a lot too).

**Review by fellowseb — APPROVED** [review]

File: opencti-platform/opencti-graphql/src/manager/historyManager.ts (hunk 1 above)
Comment (xfournet) [reply opencti-platform/opencti-graphql/src/manager/historyManager.ts:187]: i don't think this would be useful since the problem is well understood now, it wouldn't lead to any further investigation

File: opencti-platform/opencti-graphql/src/manager/historyManager.ts
Comment (xfournet) [reply opencti-platform/opencti-graphql/src/manager/historyManager.ts:151]: why not, if we are efficient to target the most important data format to check, eg when inserting/updating data in ES/Redis/Rabbit could be something feasible ?
