### PR TITLE
[backend] add noThrow opts in elLoadById (#12482)

### LINKED ISSUE #12482: Garbage collector fails to delete one element and show error for ever
## Description

This error is trigger in loop, the garbage collector fails to delete this element because of having 2 files with same name (probably with only a difference on lower/upper case).

```
{
  "category": "APP",
  "cause": {
    "attributes": {
      "genre": "TECHNICAL",
      "hits": 2,
      "http_status": 500,
      "id": "xxxxxx"
    },
    "code": "DATABASE_ERROR",
    "message": "Id loading expect only one response",
    "name": "DATABASE_ERROR",
    "stack": "GraphQLError: Id loading expect only one response\n    at error (/opt/opencti/build/back.js:1844:2273)\n    at DatabaseError (/opt/opencti/build/back.js:1844:3381)\n    at elLoadById (/opt/opencti/build/back.js:2035:2895)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async internalLoadById (/opt/opencti/build/back.js:2073:107056)\n    at async loadFile (/opt/opencti/build/back.js:2636:34127)\n    at async deleteFile (/opt/opencti/build/back.js:2636:30102)\n    at async deleteFiles (/opt/opencti/build/back.js:2636:30764)\n    at async processDeleteOperation (/opt/opencti/build/back.js:3709:34368)\n    at async confirmDelete (/opt/opencti/build/back.js:3709:34632)\n    at async Object.garbageCollectionHandler [as handler] (/opt/opencti/build/back.js:3849:5289)\n    at async cronHandler (/opt/opencti/build/back.js:2077:37265)\n    at async /opt/opencti/build/back.js:2077:39188\n    at async _SetIntervalAsyncTimer.runHandlerAndScheduleTimeout_fn (/opt/opencti/build/back.js:891:36488)\n    at async Timeout._onTimeout (/opt/opencti/build/back.js:891:36275)"
  },
  "id": "xxxxxx",
  "level": "error",
  "manager": "GARBAGE_MANAGER",
  "message": "[OPENCTI-MODULE] Garbage collection delete error",
  "source": "backend",
  "timestamp": "2025-09-19T06:56:29.820Z",
  "version": "6.7.19"
}
```

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: 6.7.19
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

## Expected Output

Maybe warn that there is an issue, but succeed to delete data.

## Actual Output

Error in loop

### PR DESCRIPTION
**Pull request by JeremyCloarec**
### Proposed changes

* add noThrow option in elLoadById to still be able to load document even if there are multiple returned
* use noThrow option when deleting a file to still be able to delete in case of duplicates

### Related issues

* #12482
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/database/engine.js [hunk 1]
```diff
@@ -1852,7 +1852,11 @@ export const elLoadById = async (context, user, id, opts = {}) => {
   const hits = await elFindByIds(context, user, id, { ...opts, withoutRels: false });
   //* v8 ignore if */
   if (hits.length > 1) {
-    throw DatabaseError('Id loading expect only one response', { id, hits: hits.length });
+    if (opts.noThrow) {
```
Comment (xfournet) [inline opencti-platform/opencti-graphql/src/database/engine.js]: option name could be more specific, eg ignoreDuplicates ?

File: opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts [hunk 2]
```diff
@@ -75,14 +75,14 @@ export const indexFileToDocument = async (context: AuthContext, file: any) => {
 };
 
 export const deleteDocumentIndex = async (context: AuthContext, user: AuthUser, id: string) => {
-  const internalFile = await storeLoadById(context, user, id, ENTITY_TYPE_INTERNAL_FILE);
+  const internalFile = await storeLoadById(context, user, id, ENTITY_TYPE_INTERNAL_FILE, { noThrow: true });
```
Comment (xfournet) [inline opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts]: should we delete the duplicates too ?

Comment (JeremyCloarec) [reply opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts]: it's not very clean, but I moved from using storeLoadById to using elFindByIds here to be able to get all the duplicates if there are any

**Review by xfournet — APPROVED** [review]
