### PR TITLE
[backend] fix Remote_logout following authentication conversion (#14756)

### LINKED ISSUE #14756: [Authentication] Conversion error during local strategy conversion
## Description

When updating to V7 we are converting environment variables to the DB but part of the conversion is case sensitive which causes issues.

For example:
this will cause an issue (cf screenshot) => PROVIDERS__OPENID__CONFIG__LOGOUT_REMOTE=False
but this will work => PROVIDERS__OPENID__CONFIG__LOGOUT_REMOTE=false

## Screenshots
Image

## Additional information
You can see more details here https://teams.microsoft.com/l/message/19:cy7Q9OdE7JZaqHaJN_sIHpwCJS_23PQbw4Rl8vV7VPw1@thread.tacv2/1772549689342?tenantId=f2a29c7e-5230-41d3-b5d1-4b6e2c4e6b7c&groupId=&parentMessageId=1772549689342&teamName=Team%20-%20XTM%20Hub&channelName=1%EF%B8%8F%E2%83%A3%20%F0%9F%AA%84%20OpenCTI%20SSO

### PR DESCRIPTION
**Pull request by CelineSebe**
### Proposed changes

* Improvement of the get function for Boolean data

### Related issues

* Fix  #14756 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Review by xfournet — APPROVED** [review]

File: opencti-platform/opencti-graphql/src/modules/authenticationProvider/authenticationProvider-migration-converter.ts [hunk 1]
```diff
@@ -104,17 +104,26 @@ export class ConfigExtractor {
...
+        if (alias in this.config) {
+          value = this.config[alias];
+        }
       }
     }
-    return defaultValue as T;
+    if (value === undefined) {
+      return defaultValue as T;
+    }
+    // Auto-convert string → boolean when the expected type is boolean
```
Comment (xfournet) [inline opencti-platform/opencti-graphql/src/modules/authenticationProvider/authenticationProvider-migration-converter.ts:122]: do we need to process numbers too ?

Comment (xfournet) [reply opencti-platform/opencti-graphql/src/modules/authenticationProvider/authenticationProvider-migration-converter.ts:122]: useless since we never map numbers

**Review by richard-julien — APPROVED** [review]
