### PR TITLE
[backend] apply fix from filterMembersUsersWithUsersOrgs to fetchMembersWithOrgaRestriction (#15599)

### LINKED ISSUE #15599: User visibility outside Org segregation: authorized members
## Description

Without org segregation, when platform is set to not disclose users pertaining to othr orgs, you can still see them in Authorized member.

## Environment

Latest

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go in a platform without paltform org
2. Ensure that **Allow users to view users of other organizations** is not enabled
3. Create a draft with a user via step by step, until you reach th step where you can define authorized members

## Expected Output

You can only see users from your own org or without org. 

## Actual Output

You can see all users.  

## Additional information

Applies to all the place where Authorized Members can be set.

### PR DESCRIPTION
**Pull request by JeremyCloarec**
### Proposed changes

* apply fix from filterMembersUsersWithUsersOrgs to fetchMembersWithOrgaRestriction
*

### Related issues

* fix #15599
*

### Checklist

- [x] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Review by fellowseb — APPROVED** [review]

File: opencti-platform/opencti-graphql/tests/03-integration/02-resolvers/user-test.ts [hunk 1]
```diff
@@ -721,8 +721,9 @@ describe('User list members query behavior', () => {
   it('Should user lists all members', async () => {
```
Comment (OctaveLaventure) [inline opencti-platform/opencti-graphql/tests/03-integration/02-resolvers/user-test.ts:721]: maybe rename the test to `Should list allowed members according to organization restriction` or something else than `list all members` now that we don't

**Review by OctaveLaventure — APPROVED** [review]
