### PR TITLE
[frontend] fix raw data json in activity log drawer (#14768)

### LINKED ISSUE #14768: Activity: no more raw details anymore
## Description

When accessing a log in activity, there is no more raw details
## Environment

Testing 
## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. With a user having access to Activity, go to activity
2. click on a log
3. Look a the drawer

## Expected Output

It should contain the raw detail
## Actual Output

I does not contain the raw details 

## Additional information

Image

### PR DESCRIPTION
**Pull request by CelineSebe**
### Proposed changes

* display the raw data detail activity or history

### Related issues

* Fixes #14768 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/settings/activity/audit/AuditDrawer.tsx [hunk 1]
```diff
@@ -103,10 +103,12 @@ const AuditDrawerContent: FunctionComponent<{ logId: string }> = ({ logId }) =>
         />
       )}
 
-      {log.entity_type === 'Activity' && (
```
Comment (JeremyCloarec) [inline opencti-platform/opencti-front/src/private/components/settings/activity/audit/AuditDrawer.tsx:106]: Are we sure that this wasn't intended? It might to worth it to discuss it further with product team

Comment (CelineSebe) [reply opencti-platform/opencti-front/src/private/components/settings/activity/audit/AuditDrawer.tsx:106]: since commit e87b2dbcc1 (12 February), we no longer display the raw data when it’s a history log, yet on this screen, according to product team, we want to display it as we did before

Comment (CelineSebe) [reply opencti-platform/opencti-front/src/private/components/settings/activity/audit/AuditDrawer.tsx:106]: It's ok with the product team

**Review by aHenryJard — APPROVED** [review]
Tested live with @nino-filigran it's all good to me.
