### PR TITLE
[backend]  Fix for escaping content in webhook variables

### LINKED ISSUE #11374: Webhook wouldn't trigger if more than one line in content
## Description

Webhook doesn't trigger when multiple lines are within the content of a note (observed in Teams and Mattermost)

## Environment

2. OpenCTI version: 6.6.16

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a webhook notifier. 
2. Create a trigger for notes. 
3. Add more than one line in the content of a note. 

## Expected Output

Receive a Teams/Mattermost notification by webhook 

## Actual Output

No notification on Teams. Webhook wouldn't trigger. 

## Additional information

In my test I pull the content of a note. 
Webhook is in "testing" under the name "Einat Test (please don't delete)" 

## Screenshots (optional)

Image

### PR DESCRIPTION
**Pull request by maelv-filigran**
### Proposed changes

*  Fix for escaping content in webhook variables

### Related issues

* #11374

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/manager/publisherManager.ts [hunk 1]
```diff
@@ -48,135 +47,264 @@ const PUBLISHER_ENABLE_BUFFERING = conf.get('publisher_manager:enable_buffering'
...
+    const { notification_id, instance, type, message } = data[i];
+    const eventNotification = notificationMap.get(notification_id);
+    if (eventNotification) {
+      const event: NotificationContentEvent = {
+        operation: type,
+        message,
+        instance_id: instance.id
+      };
+
+      const notificationUser = await findById(context, SYSTEM_USER, user.user_id);
```
Comment (labo-flg) [inline opencti-platform/opencti-graphql/src/manager/publisherManager.ts]: Could this be out of the for loop ? To avoid fetching from DB the same user every iteration.

Comment (SouadHadjiat) [reply opencti-platform/opencti-graphql/src/manager/publisherManager.ts]: solved

**Review by SouadHadjiat — APPROVED** [review]
tested locally

**Review by ValentinBouzinFiligran — APPROVED** [review]
