### PR TITLE
[frontend] add provider for safe usage of computeLink

### LINKED ISSUE #12887: Additional issues with Public Dashboard and v6.8.7
## Description

There is an issue with Public Dashboard in the List (distribution) widget. In the Custom Dashboard view it works, but when viewing it as a Public Dashboard the widget throws the error [Please provide a support package to your administrator or OpenCTI maintainers].

Web browser Developer Tools says this:

front-ULRIAZ2G.js:1  Error: Invalid user context !
    at useAuth (front-ULRIAZ2G.js:1:2238562)
    at useSchema (front-ULRIAZ2G.js:1:11503920)
    at useComputeLink (front-ULRIAZ2G.js:1:11504550)
    at WidgetDistributionList (front-ULRIAZ2G.js:1:12321207)
    at renderWithHooks (front-ULRIAZ2G.js:1:72582)
    at updateFunctionComponent (front-ULRIAZ2G.js:1:104836)
    at beginWork (front-ULRIAZ2G.js:1:116136)
    at performUnitOfWork (front-ULRIAZ2G.js:1:153243)
    at workLoopSync (front-ULRIAZ2G.js:1:152172)
    at renderRootSync (front-ULRIAZ2G.js:1:151972)
defaultOnCaughtError @ front-ULRIAZ2G.js:1

The purpose of Public Dashboard would be that it doesn't require any user or authentication...

## Environment

1. OS (where OpenCTI server runs): Ubuntu 24.04.3
2. OpenCTI version: 6.8.7

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a List (distribution) widget on a Custom Dashboard
2. Make it Public
3. Go to the public dahsboard
4. View the error

### PR DESCRIPTION
**Pull request by OctaveLaventure**
### Proposed changes

* add provider for safe usage of `computeLink` in components called on both private and public paths and that use links generation

### Related issues

* https://github.com/orgs/OpenCTI-Platform/projects/8/views/50?pane=issue&itemId=134936493&issue=OpenCTI-Platform%7Copencti%7C12887

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Context

-  There was previously a blank page when creating a clickable link to a relationship with another relationship as their `from` (issue: https://github.com/OpenCTI-Platform/opencti/issues/12616 )
-  This was fixed in https://github.com/OpenCTI-Platform/opencti/issues/12684, but the solution requires the `isRelationship` function from `useSchema` > `useAuth`, which breaks public dashboards using widgets dependent on `computeLink`

### CODE REVIEW

File: opencti-platform/opencti-front/src/utils/hooks/useIsPublicRoute.ts [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+ * ```tsx
+ * const isPublic = useIsPublicRoute();
+ * if (isPublic) {
+ *   // Handle public route logic
+ * }
+ * ```
+ */
+const useIsPublicRoute = (): boolean => {
+  const location = useLocation();
+  return location.pathname.startsWith('/public');
```
Comment (xfournet) [inline opencti-platform/opencti-front/src/utils/hooks/useIsPublicRoute.ts]: could be safer by testing on '/public/'

Comment (OctaveLaventure) [reply opencti-platform/opencti-front/src/utils/hooks/useIsPublicRoute.ts]: Done

File: opencti-platform/opencti-front/src/utils/hooks/WithPublicSafeComputeLink.tsx
Comment (xfournet) [inline opencti-platform/opencti-front/src/utils/hooks/WithPublicSafeComputeLink.tsx:1]: i fear it need to be handled case by case for all potentially public component.
could we find a solution that address the problem without need to wrap the component ?

**Comment by OctaveLaventure** [comment]
Updated the solution to avoid using render props by using a react context and a more global provider (thanks @esrevi for the great idea!)

File: opencti-platform/opencti-front/src/utils/hooks/useIsPublicRoute.ts [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+ *
+ * @example
+ * ```tsx
+ * const isPublic = useIsPublicRoute();
+ * if (isPublic) {
+ *   // Handle public route logic
+ * }
+ * ```
+ */
+const useIsPublicRoute = (): boolean => {
```
Comment (esrevi) [inline opencti-platform/opencti-front/src/utils/hooks/useIsPublicRoute.ts]: do we need still need this hook ? if not used, I think we could remove it

Comment (OctaveLaventure) [reply opencti-platform/opencti-front/src/utils/hooks/useIsPublicRoute.ts]: Indeed, I deleted it, thanks!

**Review by esrevi — APPROVED** [review]
lgtm

File: opencti-platform/opencti-front/src/utils/hooks/useComputeLink.tsx [hunk 3]
```diff
@@ -41,4 +43,38 @@ const useComputeLink = () => {
...
+  const computeLink = useComputeLinkFn();
+  return (
+    <ComputeLinkContext.Provider value={computeLink as ComputeLinkFn}>
+      {children}
+    </ComputeLinkContext.Provider>
+  );
+};
+
+export const ComputeLinkProvider = ({ children }: { children: ReactNode }) => {
+  const location = useLocation();
```
Comment (xfournet) [inline opencti-platform/opencti-front/src/utils/hooks/useComputeLink.tsx:68]: useLocation triggers a rerender on every navigation, which could cause unnecessary rerendering.

Since we only instantiate ComputeLinkProvider in two places, we could simply pass a prop to indicate whether it's a public or private one.

**Comment by xfournet** [comment]
The context-based approach looks much cleaner

File: opencti-platform/opencti-front/src/utils/hooks/useComputeLink.tsx (hunk 3 above)
Comment (xfournet) [reply opencti-platform/opencti-front/src/utils/hooks/useComputeLink.tsx:68]: (sorry for the after merge comment, it was left in pending comments...)

Comment (OctaveLaventure) [reply opencti-platform/opencti-front/src/utils/hooks/useComputeLink.tsx:68]: Handled in https://github.com/OpenCTI-Platform/opencti/pull/12914

Comment (xfournet) [reply opencti-platform/opencti-front/src/utils/hooks/useComputeLink.tsx:68]: thanks!
