### PR TITLE
[backend] fix post filtering in elPaginate (#12701)

### LINKED ISSUE #12701: In regards of filter returns empty result when used with another filter in "OR" mode
## Description

If you try to list entities with filter "in regards of" and combine it with another filter with "OR", you will get no results, even though a number of results is displayed

Image

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: 6.8 +
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. List entities with in regards of filter (ex: uses a specific attack pattern) => you see results
2. Add another filter on entity_type -> with "AND" you might see results that match both filters, but with "OR" you see no results, but you can see the counter of total results is > 0

## Expected Output

We should see results for "in regards of" OR the other filter

## Actual Output

no results

### PR DESCRIPTION
**Pull request by JeremyCloarec**
### Proposed changes

* add tagging mechanism to identify queries that exclude the need for post filters to apply to a hit

Quick summary of the tagging algo:
image
Ping me if more info needed

### Related issues

* #12701
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Review by SouadHadjiat — APPROVED** [review]
tested locally ✅

File: opencti-platform/opencti-graphql/src/database/engine.ts [hunk 1]
```diff
@@ -2542,6 +2541,70 @@ const buildSubQueryForFilterGroup = (
   }
   return null;
 };
+const buildSubQueryForTaggedFilterGroup = (
```
Comment (xfournet) [inline opencti-platform/opencti-graphql/src/database/engine.ts]: would be possible to mutualize with buildSubQueryForFilterGroup ?

File: opencti-platform/opencti-graphql/src/database/engine.ts [hunk 2]
```diff
@@ -2797,9 +2862,16 @@ const elQueryBodyBuilder = async (context: AuthContext, user: AuthUser, options:
...
-    const filtersSubQuery = buildSubQueryForFilterGroup(context, user, finalFilters);
-    if (filtersSubQuery) {
-      mustFilters.push(filtersSubQuery);
+    if (handlePostFiltering) {
+      const { subQuery: filtersSubQuery } = buildSubQueryForTaggedFilterGroup(context, user, finalFilters);
+      if (filtersSubQuery) {
+        mustFilters.push(filtersSubQuery);
+      }
+    } else {
+      const filtersSubQuery = buildSubQueryForFilterGroup(context, user, finalFilters);
```
Comment (xfournet) [inline opencti-platform/opencti-graphql/src/database/engine.ts]: if we could align the signature at least, it would permit to do:

```
  // Handle filters
  if (isFilterGroupNotEmpty(completeFilters)) {
    const finalFilters = await completeSpecialFilterKeys(context, user, completeFilters);
    const { subQuery: filtersSubQuery } = handlePostFiltering ? buildSubQueryForTaggedFilterGroup(context, user, finalFilters) : buildSubQueryForFilterGroup(context, user, finalFilters);
    if (filtersSubQuery) {
      mustFilters.push(filtersSubQuery);
    }
  }
```

but if we can forward the handlePostFiltering bool to buildSubQueryForTaggedFilterGroup/buildSubQueryForFilterGroup it would be event better ?

File: opencti-platform/opencti-graphql/src/database/engine.ts [hunk 3]
```diff
@@ -2734,12 +2797,13 @@ type QueryBodyBuilderOpts = ProcessSearchArgs & BuildDraftFilterOpts & {
...
   types?: string[] | null;
   search?: string | null;
-  filters?: FilterGroup | null;
+  filters?: TaggedFilterGroup | FilterGroup | null;
   noFiltersChecking?: boolean;
   startDate?: any;
   endDate?: any;
   dateAttribute?: string | null;
   includeAuthorities?: boolean | null;
+  handlePostFiltering?: boolean;
```
Comment (xfournet) [inline opencti-platform/opencti-graphql/src/database/engine.ts]: it's only set by elPaginate, does mean that all other usage cannot use regardingOf filtering ?

File: opencti-platform/opencti-graphql/src/database/engine.ts [hunk 4]
```diff
@@ -2505,42 +2504,74 @@ export const buildLocalMustFilter = (validFilter: any) => {
...
     }
   }
   // Handle filters
   for (let index = 0; index < filters.length; index += 1) {
     const filter = filters[index];
-    const isValidFilter = filter?.values || filter?.nested?.length > 0;
+    const isValidFilter = filter?.values || (filter?.nested && filter?.nested?.length > 0);
     if (isValidFilter) {
       const localMustFilter = buildLocalMustFilter(filter);
+      if (filter?.postFilteringTag) {
```
Comment (xfournet) [inline opencti-platform/opencti-graphql/src/database/engine.ts]:
```suggestion
      if (filter.postFilteringTag) {
```

File: opencti-platform/opencti-graphql/src/database/engine.ts [hunk 5]
```diff
@@ -2505,42 +2504,74 @@ export const buildLocalMustFilter = (validFilter: any) => {
...
   context: AuthContext,
   user: AuthUser,
-  inputFilters: any,
-) => {
+  inputFilters: TaggedFilterGroup,
+): { subQuery: any; postFiltersTags: Set<string> } => {
   const { mode = 'and', filters = [], filterGroups = [] } = inputFilters;
   const localMustFilters: any = [];
+  const localSubQueries: { subQuery: any; associatedTags: Set<string> }[] = [];
+  const localPostFilterTags: Set<string> = new Set<string>();
```
Comment (xfournet) [inline opencti-platform/opencti-graphql/src/database/engine.ts]:
```suggestion
  const localPostFilterTags = new Set<string>();
```

**Review by xfournet — APPROVED** [review]
