### PR TITLE
[frontend] fix draft creation forms (#15223)

### LINKED ISSUE #15223: Draft : fix creation forms
## Use case

- fix draft creation form
- save all metadata

### PR DESCRIPTION
**Pull request by frapuks**
### Proposed changes

* Fix step by step form
* Fix launch an import form

### Related issues

* #15223 
* #14058 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/common/files/LaunchImportDialog.tsx [hunk 1]
```diff
@@ -139,8 +139,42 @@ const LaunchImportDialog: React.FC<LaunchImportDialogProps> = ({
...
+        ? schema.required(t_i18n('This field is required'))
+        : schema,
+      otherwise: () => Yup.string().nullable(),
+    });
+
+    const draftShape = {
+      name: requiredWhenDraftAndMandatory('name', Yup.string().trim().min(2, t_i18n('Name must be at least 2 characters'))),
+      description: requiredWhenDraftAndMandatory('description', Yup.string()),
+      objectAssignee: Yup.array().when('validation_mode', {
+        is: isDraft,
```
[the remark this answers is not in the document]
Comment (frapuks) [reply opencti-platform/opencti-front/src/private/components/common/files/LaunchImportDialog.tsx:154]: authorized_members cannot be set as mandatory

File: opencti-platform/opencti-front/src/private/components/common/files/LaunchImportDialog.tsx [hunk 2]
```diff
@@ -139,8 +139,42 @@ const LaunchImportDialog: React.FC<LaunchImportDialogProps> = ({
...
+    const requiredWhenDraftAndMandatory = (field: string, schema: Yup.StringSchema) => Yup.string().when('validation_mode', {
+      is: isDraft,
+      then: () => mandatoryAttributes.includes(field)
+        ? schema.required(t_i18n('This field is required'))
+        : schema,
+      otherwise: () => Yup.string().nullable(),
+    });
+
+    const draftShape = {
+      name: requiredWhenDraftAndMandatory('name', Yup.string().trim().min(2, t_i18n('Name must be at least 2 characters'))),
```
Comment (OctaveLaventure) [inline opencti-platform/opencti-front/src/private/components/common/files/LaunchImportDialog.tsx]: **1. Clean up**

Likely useless / error-prone as we don't render a name field nor send a name in the mutation. 
The `name: ''` initialization is probably not needed either.
Doesn't it make the submission fail?

Comment (frapuks) [reply opencti-platform/opencti-front/src/private/components/common/files/LaunchImportDialog.tsx]: removed

File: opencti-platform/opencti-front/src/private/components/common/files/LaunchImportDialog.tsx [hunk 3]
```diff
@@ -188,8 +195,7 @@ const LaunchImportDialog: React.FC<LaunchImportDialogProps> = ({
   const invalidCsvMapper = selectedConnector?.name === 'ImportCsv'
     && selectedConnector?.configurations?.length === 0;
 
-  const draftInitialValues = useDefaultValues<DraftAddInput>(DRAFTWORKSPACE_TYPE, {
-    name: '',
+  const draftInitialValues = useDefaultValues<DraftAddInputWithoutName>(DRAFTWORKSPACE_TYPE, {
```
Comment (OctaveLaventure) [inline opencti-platform/opencti-front/src/private/components/common/files/LaunchImportDialog.tsx]: **1. Typing**

You may want to give [Omit](https://www.typescriptlang.org/docs/handbook/utility-types.html#omittype-keys) a try here instead of creating a new type, for example
`const draftInitialValues = useDefaultValues<Omit<DraftAddInput, 'name'>>(...`

Comment (frapuks) [reply opencti-platform/opencti-front/src/private/components/common/files/LaunchImportDialog.tsx]: fixed

**Review by OctaveLaventure — APPROVED** [review]
