### PR TITLE
[frontend] temporary fix for hidden controlled dial button

### LINKED ISSUE #13007: Missing “+” button to create object on the fly when adding a relationship
## Description

It’s no longer possible to create new entities “on the fly” when adding a relationship to an existing entity.

Previously, a “+” button was available in the bottom-right corner of the side panel to create a new relation directly from the relationship creation view. This button has now disappeared.

Image

## Environment

OCTI 6.8.8

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to an Intrusion Set entity.
2. Open the Knowledge tab, then go to the Malware section.
3. Click the “+” button in the bottom-right corner to add a relationship.
-> In the side panel, if the malware you want to relate does not exist yet, there is no option to create it. The “+” button that used to allow creating a new entity is not here anymore.

## Expected Output

The “+” button should be visible in the side panel, allowing users to create a new entity (e.g., Malware, Tool, Campaign, etc.) when it does not already exist.

## Actual Output

The “+” button is missing, preventing users from creating new entities directly during the relationship creation process.

### PR DESCRIPTION
**Pull request by OctaveLaventure**
This bug is already fixed in PR https://github.com/OpenCTI-Platform/opencti/pull/10870 which is merged in release/current, so this is just to fix this bug for clients until the next release

### Proposed changes

* fix the `Create <entity>` button on the Create Relationship view. I kept the fix super minimal as this is quite urgent and to minimize conflicts when we will merge the next release, as this bug has already been fixed in https://github.com/OpenCTI-Platform/opencti/pull/10870 with a pretty big refacto, so this will reduce the conflicts scope

### Related issues

* closes https://github.com/OpenCTI-Platform/opencti/issues/13007

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx [hunk 1]
```diff
@@ -846,6 +846,8 @@ const StixCoreRelationshipCreationFromEntity: FunctionComponent<StixCoreRelation
               speeddial={undefined}
               handleClose={undefined}
               onCompleted={undefined}
+              // TODO: remove after next release
```
Comment (Archidoit) [inline opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx]:
```suggestion
              // TODO: remove after 6.9
```

File: opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx [hunk 2]
```diff
@@ -906,6 +908,8 @@ const StixCoreRelationshipCreationFromEntity: FunctionComponent<StixCoreRelation
                 isFromBulkRelation={undefined}
                 defaultMarkingDefinitions={undefined}
                 stixDomainObjectTypes={undefined}
+                // TODO: remove after next release
```
Comment (Archidoit) [inline opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx]: same

**Review by Archidoit — APPROVED** [review]
