### PR TITLE
[frontend] also check third level in filters (#15488)

### LINKED ISSUE #15488: No possibility to request enrichment if you use "select all" checkbox in report
## Description
Issue when using 'select all' to bulk enrich.  The enrich icon is not there when using select all, it is avail when selecting all items one by one (they are all of the same type, no filter applied)
Tested on Observables tab in a report
[https://[csm](https://csm.octi.staging.filigran.io/dashboard/analyses/reports/c38b7d1a-9eae-4134-98a9-5fbae03c99d9/observables?filters=%7B%22mode%22%3A%22and%22%2C%22filters%22%3A%5B%7B%22id%22%3A%22d9862da4-a1db-4de2-8848-d738af214e3f%22%2C%22key%22%3A%22entity_type%22%2C%22operator%22%3A%22eq%22%2C%22values%22%3A%5B%5D%2C%22mode%22%3A%22or%22%7D%5D%2C%22filterGroups%22%3A%5B%5D%7D&searchTerm=&sortBy=created_at&orderAsc=false).octi.staging.filigran.io/dashboard/analyses/reports/c38b7d1a-9eae-4134-98a9-5fbae03c99d9/observables?filters=%7B%22mode%22%3A%22and%22%2C%22filters%22%3A%5B%7B%22id%22%3A%22d9862da4-a1db-4de2-8848-d738af214e3f%22%2C%22key%22%3A%22entity_type%22%2C%22operator%22%3A%22eq%22%2C%22values%22%3A%5B%5D%2C%22mode%22%3A%22or%22%7D%5D%2C%22filterGroups%22%3A%5B%5D%7D&searchTerm=&sortBy=created_at&orderAsc=false](url)

## Environment
1. 6.9.28, also tested on 7.260401.0

## Additional information
Linked to bug (regression)
https://github.com/OpenCTI-Platform/opencti/issues/5582

### PR DESCRIPTION
**Pull request by JeremyCloarec**
### Proposed changes

* also check third level in filters: it's needed in containers entities/observable page, where the user filters are nested in the third level (1st level filter is SDO/SCO, 2nd level filter is used for objects filter, and user filters are at 3rd level)
*

### Related issues

* fix #15488
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx [hunk 1]
```diff
@@ -319,6 +319,32 @@ export const getEntityTypeTwoFirstLevelsFilterValues = (
     if (filters.mode === 'or') {
       return [];
     }
+    // Check third level values
```
Comment (Archidoit) [inline opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx:322]: add fontend utils tests for this use case

**Review by Archidoit — APPROVED** [review]
