### PR TITLE
[frontend] fix spacing and add DataTable in Vocabulary Categories (#10713)

### LINKED ISSUE #10713: Vocabularies lines content is not centered
## Reproducible Steps
Go under Settings > Taxonomies > Vocabularies > a given ov

The content of each vocabulary line is not vertically centered : 

Image

### PR DESCRIPTION
**Pull request by delemaf**
### Proposed changes

* Migrate VocabularyCategories to DataTable to use dataTableUtils formatting 

### Related issues

* #10713 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/settings/VocabularyCategories.tsx [hunk 1]
```diff
@@ -1,103 +1,96 @@
...
+    entity_types: {
+      id: 'entity_types',
+      percentWidth: 20,
+      isSortable: true,
+    },
+    description: {
+      id: 'description',
+      percentWidth: 60,
+      isSortable: false,
+      render: (data: { category: VocabularyDefinition }) => (data.category.description ? t_i18n(data.category.description) : ''),
```
Comment (Archidoit) [inline opencti-platform/opencti-front/src/private/components/settings/VocabularyCategories.tsx]: use defaultRender to handle empty description and truncate and tooltip

Comment (Archidoit) [inline opencti-platform/opencti-front/src/private/components/settings/VocabularyCategories.tsx]:
```suggestion
      render: (data: { category: VocabularyDefinition }) => (data.category.description ? t_i18n(data.category.description) : ''),
```
```suggestion
      render: (data: { category: VocabularyDefinition }) => useDefaultRender(data.category.description),
```

**Review by Archidoit — CHANGES_REQUESTED** [review]

**Review by Archidoit — APPROVED** [review]
