### PR TITLE
[backend] fix manual & auto enrichment (#13008)

### LINKED ISSUE #13008: Manual enrichment fails with error 'No bundle resolver for type X"
## Description

Manual enrichment is broken
## Environment

Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. try to manually enrich an observable

## Expected Output

it works
## Actual Output

it fails

### PR DESCRIPTION
**Pull request by JeremyCloarec**
### Proposed changes

* fix an issue in askElementEnrichmentForConnectors with the introduction of stixBundleByIdStringify
* => now only compute stix_objects if required by the connector
* => now return null instead of throwing an error in stixBundleByIdStringify if no bundleResolver is defined for entity type
* fix an issue in filterConnectorsForElementEnrichment where autoTrigger could be computed to true even if connectors are not configured with auto_update = true
* => changed autoTrigger to match previous behavior

### Related issues

* #13008
*

### Checklist

- [x] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/database/middleware.js [hunk 1]
```diff
@@ -544,8 +544,10 @@ export const stixLoadByIds = async (context, user, ids, opts = {}) => {
 };
 export const stixBundleByIdStringify = async (context, user, type, id) => {
   const resolver = modules.get(type)?.bundleResolver;
-  if (resolver) return await resolver(context, user, id);
-  throw UnsupportedError('No bundle resolver for type', { type });
+  if (resolver) {
```
Comment (esrevi) [inline opencti-platform/opencti-graphql/src/database/middleware.js]: I think inverting as early return pattern is easier for readability and keeps the happy path at the main indentation level :)

```suggestion
  if (!resolver) {
    return null
  }
  
  return await resolver(context, user, id);
```

**Review by SouadHadjiat — APPROVED** [review]
tested locally ✅
