### PR TITLE
[backend] Fix RSS parsing crash when items lack title elements (#10830)

### LINKED ISSUE #10830: Issues parsing RSS feed when <ITEM> tags contain no <Title> element
## Description
When setting up an RSS feed using: 
https://infosec.exchange/users/monitorsg.rss
Nothing is ingested into the platform, no activity shown for this feed.

## Environment
1. SaaS 6.6.7

Steps to create the smallest reproducible scenario:
1. Set up a RSS feed using above URL

## Expected Output
RSS feed to be ingested

## Actual Output
Nothing is ingested

## Additional information
If the title is not provided in each item element, maybe, as discussed internally, the title tag could be populated from the link tag

### PR DESCRIPTION
**Pull request by maelv-filigran**
### Proposed changes

* Fixed RSS feed parser crash when `<title>` element is missing from RSS/Atom items
* Added fallback logic: uses link URL when title is absent, or "Untitled" as last resort
* Updated test expectations to reflect that all 44 items are now correctly processed (previously 43 due to crash)

### Related issues

Fixes #10830

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

**Root Cause:**
The RSS parser was directly accessing `entry.title._` and `item.title._` without checking if the `title` property exists. When RSS items lack a `<title>` tag entirely, the XML parser returns `undefined`, causing a `TypeError: Cannot read property '_' of undefined`. This crash prevented the entire feed from being processed.

**Solution:**
Implemented safe property access using optional chaining (`?.`) with a fallback cascade:
1. Use the title if present
2. Fall back to the link URL if title is missing (as suggested in the issue)
3. Use "Untitled" as final fallback

**Testing:**
The existing test data (`rss-wago.xml`) already contained an item without a title (line 148), which was causing the test to expect 43 items instead of 44. The fix now correctly processes all 44 items, including the one without a title.

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/manager/ingestionManager.ts [hunk 1]
```diff
@@ -185,10 +189,14 @@ const rssItemV1Convert = (turndownService: TurndownService, feed: RssElement, en
 
 const rssItemV2Convert = (turndownService: TurndownService, channel: RssElement, item: RssItem): DataItem => {
   const { pubDate } = channel;
+  // Safe access to title with fallback to link if title is missing
+  const link = isNotEmptyField(item.link) ? ((item.link as { _: string })._ ?? '').trim() : '';
+  const title = item.title?._ || link || 'Untitled';
```
Comment (OctaveLaventure) [inline opencti-platform/opencti-graphql/src/manager/ingestionManager.ts:196]: **1. Translation**
I guess it would make sense to translate `'Untitled'`, what do you think?

File: opencti-platform/opencti-graphql/src/manager/ingestionManager.ts [hunk 2]
```diff
@@ -173,10 +173,14 @@ interface DataItem {
 
 const rssItemV1Convert = (turndownService: TurndownService, feed: RssElement, entry: RssItem): DataItem => {
   const { updated } = feed;
+  // Safe access to title with fallback to link if title is missing
+  const link = isNotEmptyField(entry.link) ? (entry.link as { href: string }).href?.trim() : '';
```
Comment (OctaveLaventure) [inline opencti-platform/opencti-graphql/src/manager/ingestionManager.ts]: **2. Typing**
- I think the cast is unnecessary, or if we really want to keep it to be explicit then we don't need the `?` after `href` as it seems inconsistent with the `href: string` casted type
- do we want to return an empty string `''` when no link is provided? We could use `undefined` as the function's return type seems to allow it, or make it allow `null` to be explicit

Comment (OctaveLaventure) [inline opencti-platform/opencti-graphql/src/manager/ingestionManager.ts]: **3. Refactor**
wouldn't `const link = entry.link?.href?.trim() ?? ''` achieve the same result? It would avoid adding more dependency to Ramda

File: opencti-platform/opencti-graphql/src/manager/ingestionManager.ts [hunk 3]
```diff
@@ -185,10 +189,14 @@ const rssItemV1Convert = (turndownService: TurndownService, feed: RssElement, en
 
 const rssItemV2Convert = (turndownService: TurndownService, channel: RssElement, item: RssItem): DataItem => {
   const { pubDate } = channel;
+  // Safe access to title with fallback to link if title is missing
+  const link = isNotEmptyField(item.link) ? ((item.link as { _: string })._ ?? '').trim() : '';
```
Comment (OctaveLaventure) [inline opencti-platform/opencti-graphql/src/manager/ingestionManager.ts]: **4. Refactor**
same as commment `3.`: `const link = item.link?._?.trim() ?? ''`

File: opencti-platform/opencti-graphql/src/manager/ingestionManager.ts (hunk 1 above)
Comment (maelv-filigran) [reply opencti-platform/opencti-graphql/src/manager/ingestionManager.ts:196]: This is backend code, we do not use i18n here, even if you suggestion total make sens, it's not possible

File: opencti-platform/opencti-graphql/src/manager/ingestionManager.ts (hunk 2 above)
Comment (maelv-filigran) [reply opencti-platform/opencti-graphql/src/manager/ingestionManager.ts]: Fixed! Removed the unnecessary cast and the inconsistent `?` operator. Now using `entry.link?.href?.trim() ?? ''` which is cleaner and type-safe.

Comment (maelv-filigran) [reply opencti-platform/opencti-graphql/src/manager/ingestionManager.ts]: one! Replaced with `entry.link?.href?.trim() ?? ''` much cleaner and removes the unnecessary Ramda dependency for this simple check.

File: opencti-platform/opencti-graphql/src/manager/ingestionManager.ts (hunk 3 above)
Comment (maelv-filigran) [reply opencti-platform/opencti-graphql/src/manager/ingestionManager.ts]: Applied! Changed to `item.link?._?.trim() ?? ''` for consistency with the v1 converter.

File: opencti-platform/opencti-graphql/src/manager/ingestionManager.ts (hunk 1 above)
Comment (OctaveLaventure) [reply opencti-platform/opencti-graphql/src/manager/ingestionManager.ts:196]: Oh sorry I assumed we did as there was translation files in `back/xx.json` but it's also in the front app 😅

**Review by OctaveLaventure — APPROVED** [review]
