### PR TITLE
[frontend] Fix workspace duplication dialog closing unexpectedly on internal clicks (#11010)

### LINKED ISSUE #11010: Not possible to edit new dashboard name when duplicating a dashboard.
## Description

When duplicating a custom dashboard, if you try to change the name that ends with "copy" the popup is gone.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 } 6.6.11
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go on custom dashboard
2. Use 3 dot menu on the right
3. Click on duplicate
4. Try to rename to whatever you want.

## Expected Output

Choose a name before duplicate.

## Actual Output

Exit duplication.

### PR DESCRIPTION
**Pull request by maelv-filigran**
### Proposed changes

* Fixed dialog closing unexpectedly when clicking inside the workspace duplication popup
* Updated event handling to properly manage dialog closure behavior while maintaining backdrop click functionality
* Prevented event propagation from dialog content to avoid unintended closures

### Related issues

* Fixes issue where the workspace duplication dialog would close when clicking inside the dialog content (title, text field, etc.)
* Preserves the expected behavior of closing the dialog when clicking on the backdrop
* #11010 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

The issue was caused by improper event handling in the MUI Dialog component. Click events inside the dialog were bubbling up and triggering the dialog's close mechanism.

**Solution implemented:**
- Modified the `handleCloseDuplicate` function signature to remove the UIEvent parameter as it wasn't compatible with MUI's onClose callback
- Updated the Dialog's `onClose` handler to properly handle both backdrop clicks and escape key events
- Added `stopPropagation()` on the Paper component through `slotProps` to prevent click events inside the dialog from bubbling up

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceDuplicationDialog.tsx [hunk 1]
```diff
@@ -113,7 +113,12 @@ WorkspaceDuplicationDialogProps
   return (
     <Dialog
       open={displayDuplicate}
-      slotProps={{ paper: { elevation: 1 } }}
+      slotProps={{
+        paper: {
+          elevation: 1,
+          onClick: (e: React.MouseEvent) => e.stopPropagation(),
```
Comment (delemaf) [inline opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceDuplicationDialog.tsx]: If you need we have a little utils function `stopEvent` that could handle this (also preventDefault)
https://github.com/OpenCTI-Platform/opencti/blob/4826b2cda6d41d610de209dc604952d4cfb434ba/opencti-platform/opencti-front/src/utils/domEvent.ts#L3-L6

**Comment by CelineSebe** [comment]
it works well :)

**Review by CelineSebe — APPROVED** [review]

**Review by delemaf — APPROVED** [review]
