### PR TITLE
[backend] Fix notifier issue with special characters (#13216)

### LINKED ISSUE #13216: Notifer issue with special character
## Description

If a csutomer notifier is supposed to send a notification that contains the description of an entity and the description contains a "/", the notification is not sent.
## Environment

Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1.Create the following custom notifier 
{
"title": "<%= data[0].instance.name %>",
"description": "<%= data[0].instance.description%>",
"id":"<%= notification_content[0].events[0].instance_id %>",
}
2. trigger a notification for an entity that has a "/" in its description 

## Expected Output

notification received
## Actual Output

notification not received
## Additional information

After investigation, it seems that special characters are not well supported. The fix should consist in using JSON.stringify rather than doing escaping.

### PR DESCRIPTION
**Pull request by maelv-filigran**
### Proposed changes

* Replace custom string escaping logic with JSON.stringify in webhook notifications
* Use EJS escape option to properly handle special characters including forward slashes
* Remove unnecessary try-catch wrapper in internalProcessNotification
* Add test case for forward slash handling

### Related issues
* #13216 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Review by JeremyCloarec — APPROVED** [review]

File: opencti-platform/opencti-graphql/src/manager/publisherManager.ts [hunk 1]
```diff
@@ -251,41 +238,37 @@ export const internalProcessNotification = async (
...
-        break;
-      case NOTIFIER_CONNECTOR_WEBHOOK:
-        await handleWebhookNotification(notifierConfigurationString, assembledTemplateData);
-        break;
-      default:
-        // TODO: Handle other notifier scenarios
-        break;
-    }
-  } catch (error) {
-    return { error: (error as Error).message };
```
Comment (xfournet) [inline opencti-platform/opencti-graphql/src/manager/publisherManager.ts:288]: this has not been reported to testNotifier in opencti-platform/opencti-graphql/src/modules/notifier/notifier-domain.ts which was the only caller to rely on return { error }. so it need to be catch in testNotifier now.
I would also removed the // eslint-disable-next-line consistent-return  and explicitly return undefined when everything is ok
