### PR TITLE
[backend] fix filterMembersWithUsersOrgs (#13338)

### LINKED ISSUE #13338: User segregation: entities not accessible since user is "null" in knowledge history
## Description

In context of segregation:
- Org A has a user that has done some changes on an entity.
Via authorize members, this entity access is granted to an other org B.
- User of org B tries to access the entity. 

The screen crashes, since the user of Org B that tries to access the entity cannot see the user of Org A in history, since the user value is "null". It should not be null, but rather should be filled with the user, but displayed as restricted for the user of OrgB. 
Users of the same Org than the user of Org A should see the name of the user who did the change. 

## Environment

Production
## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Have a paltform with Org Segregation
2. Define two Orgs, Org A and Org B.
3. Create a report with a userA of Org A. Change the status of report. 
4. With a playbook, enable authorize member on the report, and give users of OrgA read Access & user of OrgB read access
5. Login with user B (user of ORgB)
6. Try to access the report

## Expected Output

Report should be accessible, and in the history we should see "restricted" has replaced {newStatusValue} in Status

## Actual Output

Crash

Image

### PR DESCRIPTION
**Pull request by JeremyCloarec**
### Proposed changes

* fix filterMembersWithUsersOrgs logic introduced in https://github.com/OpenCTI-Platform/opencti/pull/12894
* before changes, we were correctly returning the member if it was a member in the same orgs as the user. After the change, this default return was removed, causing all members in the same orgs to be filtered out
*

### Related issues

* #13338 
*

### Checklist

- [x] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/utils/access.ts [hunk 1]
```diff
@@ -926,21 +926,24 @@ export const filterMembersWithUsersOrgs = async (
...
-              main: RESTRICTED_USER.name,
-              secondary: RESTRICTED_USER.name
-            }
-          };
-          resultMembers.push(restrictedMember);
+      } else {
+        const memberOrgIds = member[RELATION_PARTICIPATE_TO] ?? [];
+        const sameOrg = memberOrgIds.some((id) => userOrgIds.includes(id));
+        if (!sameOrg) {
+          if (filterMode === FilterMembersMode.RESTRICT) {
```
Comment (Kedae) [inline opencti-platform/opencti-graphql/src/utils/access.ts:935]: Not sure to get that part. If we are in exclude mode we will still have an empty array eventually ?

Comment (JeremyCloarec) [reply opencti-platform/opencti-graphql/src/utils/access.ts:935]: Yes, we're using the exclude mode when fetching the possible creators/participants/assignees values in filters. In this case, we want to not receive any restricted member instead of showing them as Restricted

File: opencti-platform/opencti-graphql/src/utils/access.ts [hunk 2]
```diff
@@ -926,21 +926,24 @@ export const filterMembersWithUsersOrgs = async (
...
-            representative: {
-              main: RESTRICTED_USER.name,
-              secondary: RESTRICTED_USER.name
-            }
-          };
-          resultMembers.push(restrictedMember);
+      } else {
+        const memberOrgIds = member[RELATION_PARTICIPATE_TO] ?? [];
+        const sameOrg = memberOrgIds.some((id) => userOrgIds.includes(id));
+        if (!sameOrg) {
```
Comment (OctaveLaventure) [inline opencti-platform/opencti-graphql/src/utils/access.ts]: **1. Refactoring**
avoid `if not` for clarity, I think you can reverse the if/else

**Review by OctaveLaventure — APPROVED** [review]
