### PR TITLE
[backend] fix migration for local strategy (#14737)

### LINKED ISSUE #14737: Disabled local authentication strategy is set to enable following conversion to V7
## Description

When we have a local authentication strategy setup in V6 and we update the platform to V7, the local strategy is created enabled in the UI instead of using the value from the environment variable (you would need to manually disable in the UI in order to make it disappear).

The expected result should be:
- if we have a working SSO authentication setup and we are Entreprise Edition/Trial, we set up the local disabled or enabled according to the value of the env variable
- if we have don't have a working SSO authentication or we have a community edition, the local should be enabled upon conversion regardless of its value in the env variable

**Workaround**: login as admin on OpenCTI platform (with access to security > Authentication) and edit local strategy configuration to disable it.

### PR DESCRIPTION
**Pull request by marieflorescontact**
### Proposed changes

* for an existing platform in 6.9.x, with local auth disabled => conversion set it to enabled, probably because it's config { disabled: true } and code looks for enabled here

### Related issues

* closes: https://github.com/OpenCTI-Platform/opencti/issues/14737

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Comment by marieflorescontact** [comment]
@copilot add test coverage for this PR

File: opencti-platform/opencti-graphql/src/modules/authenticationProvider/authenticationProvider-migration.ts [hunk 1]
```diff
@@ -17,6 +17,11 @@ import nconf from 'nconf';
 import { getSettings, updateCertAuth, updateHeaderAuth, updateLocalAuth } from '../../domain/settings';
 import type { BasicStoreSettings } from '../../types/settings';
 
+export const isLocalAuthEnabled = (envProviders: Record<string, any>): boolean => {
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/modules/authenticationProvider/authenticationProvider-migration.ts]:
```suggestion
export const isLocalAuthEnabledInEnv = (envProviders: Record<string, any>): boolean => {
```

Comment (aHenryJard) [reply opencti-platform/opencti-graphql/src/modules/authenticationProvider/authenticationProvider-migration.ts]: I think we really need to be clear on env vs database

**Review by aHenryJard — APPROVED** [review]
Looks good to me, tested locally:
- on a new platform V7, local is enabled by default as expected
- on an existing platform with auth0 + local disabled, after moving to this branch the local is correctly disabled (only auth0 button is displayed)
