### PR TITLE
[backend] fix network traffic src_port unknown (#12853)

### LINKED ISSUE #12853: Network traffic displayed as Unknown if no dst_port
## Description
Network traffic observables are displayed as 'Unknown' everywhere in the platform if they have no dst_port

## Reproducible Steps
- Create a network traffic with only a src_port (no dst_port)
- The network traffic is displayed as 'Unknown' everywhere: observables list, knowledge tabs, etc

Image

Image

### PR DESCRIPTION
**Pull request by CelineSebe**
### Proposed changes

* add src_port in observable value

### Related issues

* closes #12853 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/utils/format.js [hunk 1]
```diff
@@ -218,7 +218,7 @@ export const observableValue = (stixCyberObservable) => {
     case ENTITY_MUTEX:
       return stixCyberObservable.name || 'Unknown';
     case ENTITY_NETWORK_TRAFFIC:
-      return stixCyberObservable.dst_port || 'Unknown';
+      return stixCyberObservable.dst_port || stixCyberObservable.src_port || 'Unknown';
```
Comment (Archidoit) [inline opencti-platform/opencti-graphql/src/utils/format.js]: this list is duplicated in front, think about updating it aswell in Entity.ts

**Review by Archidoit — CHANGES_REQUESTED** [review]

File: opencti-platform/opencti-graphql/src/utils/format.js (hunk 1 above)
Comment (Archidoit) [inline opencti-platform/opencti-graphql/src/utils/format.js]: what about in the other order ? (src_port, than dst_port) since src_port is required and dst_port seems not... to be seen with Product

Comment (CelineSebe) [reply opencti-platform/opencti-graphql/src/utils/format.js]: I added this change. Thanks :)

Comment (CelineSebe) [reply opencti-platform/opencti-graphql/src/utils/format.js]: In the shema, no field is required. You're right about src_port being required in the UI, so I have reversed the priority. I will check with the product team.

Comment (CelineSebe) [reply opencti-platform/opencti-graphql/src/utils/format.js]: Validated by the product

**Review by Archidoit — APPROVED** [review]
