### PR TITLE
[frontend/backend] Change dashboard widget import logic to not break existing layout (#12085)

### LINKED ISSUE #12085: Dashboard layout issue when using import.
## Description

A first fix have been made to fix layout issue but it seems there are still edge cases with import as referred in this comment https://github.com/OpenCTI-Platform/opencti/issues/10730#issuecomment-3206734656.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

## Expected Output

Layout stays in place.

## Actual Output

Layout is broken by new widgets.

### PR DESCRIPTION
**Pull request by lndrtrbn**
### Proposed changes

* Front: take in account layout changes when importing widget
* Back: change imported widget position to move it on a new line at the end of dashboard (to not break existing layout)

How to reproduce bug on master:
- create a dashboard
- add some widgets
- modify their size and position
- import a widget
- _the layout rollback_

In the branch, the layout stays and the imported widget goes at the end of the layout

### Related issues

* #12085

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/utils/base64.ts [hunk 1]
```diff
@@ -0,0 +1,4 @@
+import { fromBase64, toBase64 } from '../database/utils';
+
+export const toB64 = (data: unknown): string | undefined => toBase64(JSON.stringify(data));
```
Comment (marieflorescontact) [inline opencti-platform/opencti-graphql/src/utils/base64.ts:3]: we should use this method for every usages of `toBase64(JSON.stringify(some data))`

**Review by marieflorescontact — COMMENTED** [review]
locally tested ok 👌

File: opencti-platform/opencti-graphql/src/utils/base64.ts (hunk 1 above)
Comment (lndrtrbn) [reply opencti-platform/opencti-graphql/src/utils/base64.ts:3]: done, except for migration files

**Review by marieflorescontact — APPROVED** [review]
