### PR TITLE
[frontend] add category in context filters in Vocabularies (#14451)

### LINKED ISSUE #14451: Bulk delete removes all vocabularies
## Description
When attempting to delete items from a specific vocabulary category in the settings, the deletion action incorrectly affects all vocabularies instead of just the selected one.

## Environment
6.9.15

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1: Go to settings -> taxonomies -> vocabularies.
2: Select any vocabulary category from the list (e.g., account_type_ov).
3: Click the "select all" option under this vocabulary.
4: Click the delete icon.

Image

_Bulk deletion performed on all items under account_type_ov_

Image

_Task of bulk delete operation. Note the number of entities affected by the operation, 370_

Image

_All items under attack_motivation_ov are deleted_

## Expected Output
Only the items within the selected vocabulary category (e.g., account_type_ov) should be deleted.

## Actual Output
All vocabularies are deleted, including those not under the selected category. This behavior is consistent across all vocabularies.

### PR DESCRIPTION
**Pull request by JeremyCloarec**
### Proposed changes

*  add category in context filters in Vocabularies 
*

### Related issues

* fix #14451
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/settings/Vocabularies.tsx [hunk 1]
```diff
@@ -104,7 +104,8 @@ const Vocabularies = () => {
   );
 
   const { filters } = viewStorage;
-  const contextFilters = useBuildEntityTypeBasedFilterContext('Vocabulary', filters);
+  const baseContextFIlters = useBuildEntityTypeBasedFilterContext('Vocabulary', filters);
+  const contextFilters = addFilter(baseContextFIlters, 'category', category, 'eq', 'and');
```
Comment (fellowseb) [inline opencti-platform/opencti-front/src/private/components/settings/Vocabularies.tsx]: So I'm trying to understand the code and apply the fix locally. I see this results in the display of a `filters are not fully displayed` message in the UI:

Image

with the following filter object:

```
The complete Filter object is as follows:
{
  "mode": "and",
  "filters": [
    {
      "key": "category",
      "values": [
        "account_type_ov"
      ],
      "operator": "eq",
      "mode": "and"
    }
  ],
  "filterGroups": [
    {
      "mode": "and",
      "filters": [
        {
          "key": "entity_type",
          "values": [
            "Vocabulary"
          ],
          "operator": "eq",
          "mode": "or"
        }
      ],
      "filterGroups": []
    }
  ]
}
```

Isn't there a way that would make the filter object simpler (like flattening everything) and thus displayable with current logic ?

Comment (JeremyCloarec) [reply opencti-platform/opencti-front/src/private/components/settings/Vocabularies.tsx]: I pushed a new version with simplified filter structure

Comment (fellowseb) [reply opencti-platform/opencti-front/src/private/components/settings/Vocabularies.tsx]: Great !

**Review by fellowseb — APPROVED** [review]

**Review by Archidoit — APPROVED** [review]
