### PR TITLE
[backend] Improve ids query to avoid too many nested clauses error (#10538)

### LINKED ISSUE #10538: CSV export leads to database pagination error
## Description
**Connector Error**
Upon generating a text/csv (this is the `export-file-csv` connector) report for one of our large reports, we see the following connector error
`ValueError: {'name': 'DATABASE_ERROR', 'error_message': 'Fail to execute engine pagination'}`
This pagination error which shows in the UI stems from the below DB error.
**DB Error**
We are seeing in our OpenSearch error log an error where we query 11 separate indexes, which gives the following error in the db.
`NotSerializableExceptionWrapper[too_many_nested_clauses: Query contains too many nested clauses; maxClauseCount is set to 1024]`
Stack Trace:
```[2025-03-13T12:23:18,702][WARN ][r.suppressed             ] [1a89c664c20fe61bfc2d74b7d3bf266d] path: __PATH__ params: {index=opencti_internal_objects*,opencti_internal_relationships*,opencti_stix_meta_objects*,opencti_stix_meta_relationships*,opencti_stix_cyber_observable_relationships*,opencti_stix_domain_objects*,opencti_stix_core_relationships*,opencti_stix_sighting_relationships*,opencti_stix_cyber_observables*,opencti_inferred_entities*,opencti_inferred_relationships*, _source=true, track_total_hits=true}
Failed to execute phase [query], all shards failed; shardFailures {[0Kev2EToTbaHfkKgFHigOw][opencti_internal_objects][0]: RemoteTransportException[[32a12924f8caaba39e8305bdc4bb402c][__IP__][__PATH__[__PATH__]]]; nested: NotSerializableExceptionWrapper[too_many_nested_clauses: Query contains too many nested clauses; maxClauseCount is set to 1024]; }{[5RH-aCxqQG2mRyd9VnO7sQ][opencti_stix_cyber_observables][0]: RemoteTransportException[[1ee4158a1b077062f5520bbde356523c][__IP__][__PATH__[__PATH__]]]; nested: NotSerializableExceptionWrapper[too_many_nested_clauses: Query contains too many nested clauses; maxClauseCount is set to 1024]; }{[Im6HL8hYSPi3i5HtjqK3nQ][opencti_stix_domain_objects][0]: RemoteTransportException[[98d50eeb9c58f29d3d03665fb9dc741e][__IP__][__PATH__[__PATH__]]]; nested: NotSerializableExceptionWrapper[too_many_nested_clauses: Query contains too many nested clauses; maxClauseCount is set to 1024]; }{[Im6HL8hYSPi3i5HtjqK3nQ][opencti_stix_meta_objects][0]: RemoteTransportException[[98d50eeb9c58f29d3d03665fb9dc741e][__IP__][__PATH__[__PATH__]]]; nested: NotSerializableExceptionWrapper[too_many_nested_clauses: Query contains too many nested clauses; maxClauseCount is set to 1024]; }{[0Kev2EToTbaHfkKgFHigOw][opencti_internal_relationships][0]: RemoteTransportException[[32a12924f8caaba39e8305bdc4bb402c][__IP__][__PATH__[__PATH__]]]; nested: NotSerializableExceptionWrapper[too_many_nested_clauses: Query contains too many nested clauses; maxClauseCount is set to 1024]; }{[5RH-aCxqQG2mRyd9VnO7sQ][opencti_stix_core_relationships][0]: RemoteTransportException[[1ee4158a1b077062f5520bbde356523c][__IP__][__PATH__[__PATH__]]]; nested: NotSerializableExceptionWrapper[too_many_nested_clauses: Query contains too many nested clauses; maxClauseCount is set to 1024]; }{[Im6HL8hYSPi3i5HtjqK3nQ][opencti_inferred_relationships-000001][0]: RemoteTransportException[[98d50eeb9c58f29d3d03665fb9dc741e][__IP__][__PATH__[__PATH__]]]; nested: NotSerializableExceptionWrapper[too_many_nested_clauses: Query contains too many nested clauses; maxClauseCount is set to 1024]; }{[Im6HL8hYSPi3i5HtjqK3nQ][opencti_stix_meta_relationships][0]: RemoteTransportException[[98d50eeb9c58f29d3d03665fb9dc741e][__IP__][__PATH__[__PATH__]]]; nested: NotSerializableExceptionWrapper[too_many_nested_clauses: Query contains too many nested clauses; maxClauseCount is set to 1024]; }{[Im6HL8hYSPi3i5HtjqK3nQ][opencti_stix_cyber_observable_relationships][0]: RemoteTransportException[[98d50eeb9c58f29d3d03665fb9dc741e][__IP__][__PATH__[__PATH__]]]; nested: NotSerializableExceptionWrapper[too_many_nested_clauses: Query contains too many nested clauses; maxClauseCount is set to 1024]; }{[5RH-aCxqQG2mRyd9VnO7sQ][opencti_stix_sighting_relationships][0]: RemoteTransportException[[1ee4158a1b077062f5520bbde356523c][__IP__][__PATH__[__PATH__]]]; nested: NotSerializableExceptionWrapper[too_many_nested_clauses: Query contains too many nested clauses; maxClauseCount is set to 1024]; }{[5RH-aCxqQG2mRyd9VnO7sQ][opencti_inferred_entities-000001][0]: RemoteTransportException[[1ee4158a1b077062f5520bbde356523c][__IP__][__PATH__[__PATH__]]]; nested: NotSerializableExceptionWrapper[too_many_nested_clauses: Query contains too many nested clauses; maxClauseCount is set to 1024]; }
    at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:716)
    at org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:381)
    at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:755)
    at org.opensearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:513)
    at org.opensearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:303)
    at org.opensearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:104)
    at org.opensearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:75)
    at org.opensearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:764)
    at org.opensearch.transport.TransportService$6.handleException(TransportService.java:904)
    at org.opensearch.security.transport.SecurityInterceptor$RestoringTransportResponseHandler.handleException(SecurityInterceptor.java:425)
    at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1561)
    at org.opensearch.transport.InboundHandler.lambda$handleException$3(InboundHandler.java:438)
    at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:412)
    at org.opensearch.transport.InboundHandler.handleException(InboundHandler.java:436)
    at org.opensearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:428)
    at org.opensearch.transport.InboundHandler.messageReceived(InboundHandler.java:166)
    at org.opensearch.transport.InboundHandler.inboundMessage(InboundHandler.java:123)
    at org.opensearch.transport.TcpTransport.inboundMessage(TcpTransport.java:770)
    at org.opensearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:175)
    at org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:150)
    at org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:115)
    at org.opensearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:95)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1471)
    at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1334)
    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1383)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at __PATH__(Thread.java:840)
Caused by: NotSerializableExceptionWrapper[too_many_nested_clauses: Query contains too many nested clauses; maxClauseCount is set to 1024]
    at org.apache.lucene.search.IndexSearcher$3.consumeTerms(IndexSearcher.java:844)
    at org.apache.lucene.search.TermQuery.visit(TermQuery.java:254)
    at org.apache.lucene.search.DisjunctionMaxQuery.visit(DisjunctionMaxQuery.java:250)
    at org.apache.lucene.search.BooleanQuery.visit(BooleanQuery.java:583)
    at org.apache.lucene.search.BooleanQuery.visit(BooleanQuery.java:578)
    at org.apache.lucene.search.BooleanQuery.visit(BooleanQuery.java:578)
    at org.apache.lucene.search.BooleanQuery.visit(BooleanQuery.java:578)
    at org.apache.lucene.search.BooleanQuery.visit(BooleanQuery.java:578)
    at org.apache.lucene.search.IndexSearcher.rewrite(IndexSearcher.java:804)
    at org.opensearch.search.internal.ContextIndexSearcher.rewrite(ContextIndexSearcher.java:194)
    at org.opensearch.search.DefaultSearchContext.preProcess(DefaultSearchContext.java:357)
    at org.opensearch.search.query.QueryPhase.preProcess(QueryPhase.java:127)
    at org.opensearch.search.SearchService.createContext(SearchService.java:997)
    at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:593)
    at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:566)
    at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:74)
    at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:89)
    at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
    at org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78)
    at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
    at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59)
    at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:917)
    at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:840)
```

**API Logs**
The api logs can be viewed as an attached text file

[api_log.txt](https://github.com/user-attachments/files/19653451/api_log.txt)

## Environment

1. AWS (Amazon Linux)
2. OpenCTI version: 6.2.18
3. OpenCTI client: python
4. Other environment details: Using amazon opensearch

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Generate a report in opencti (our report had 79 entities and 113 observables)
2. Go to data, export, and click export as text/csv.
3. Observe database pagination error.

## Expected Output
This should output a report for download.
## Actual Output
Stated error, where the database gives pagination failure.

### PR DESCRIPTION
**Pull request by SouadHadjiat**
### Proposed changes

* Improve Ids filter to use terms query (it's an ids filter that is used for csv export of report objects)

### Related issues

* #10538

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/database/engine.js [hunk 1]
```diff
@@ -2604,62 +2606,35 @@ const adaptFilterToEntityTypeFilterKey = (filter) => {
...
-    // similarly we need to split into filters for each additional source
-    newFilterGroup = {
-      mode: operator === 'eq' ? 'or' : 'and',
-      filters: [
-        { ...filter, key: ['ids'] },
-        [...idsArray.map((k) => ({ ...filter, key: [k] }))],
-      ],
-      filterGroups: [],
-    };
-  }
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/database/engine.js:2677]: here I just simplified this code, since mode can only be 'or', not 'and'

File: opencti-platform/opencti-graphql/src/database/engine.js [hunk 2]
```diff
@@ -2604,62 +2606,35 @@ const adaptFilterToEntityTypeFilterKey = (filter) => {
...
+  if (mode === 'and') {
     throw UnsupportedError('Unsupported filter: \'And\' operator between values of a filter with key = \'ids\' is not supported');
   }
   // at this point arrayKey === ['ids'], and mode is always 'or'
 
   // we'll build these new filters or filterGroup, depending on the situation
   let newFilterGroup;
 
-  const idsArray = [ID_INTERNAL, ID_STANDARD, IDS_STIX]; // the keys to handle additionally
+  const idsArray = [...ids_attributes]; // the keys to handle additionally
```
Comment (JeremyCloarec) [inline opencti-platform/opencti-graphql/src/database/engine.js:2638]: just an observation, but this idsArray didn't include aliases ids before, I think this wasn't intentional and was a mistake before, that's also your thinking here?

File: opencti-platform/opencti-graphql/src/database/engine.js [hunk 3]
```diff
@@ -1760,7 +1762,7 @@ export const elFindByIds = async (context, user, ids, opts = {}) => {
     const mustTerms = [];
     const workingIds = groupIds[index];
     const idsTermsPerType = [];
-    const elementTypes = [internalId.name, standardId.name, xOpenctiStixIds.name, iAliasedIds.name];
+    const elementTypes = [...ids_attributes];
```
Comment (JeremyCloarec) [inline opencti-platform/opencti-graphql/src/database/engine.js:1767]: Can't we completely remove elementTypes and just use ids_attributes instead?

File: opencti-platform/opencti-graphql/src/database/engine.js (hunk 2 above)
Comment (SouadHadjiat) [reply opencti-platform/opencti-graphql/src/database/engine.js:2638]: yes I also think aliases were forgotten

File: opencti-platform/opencti-graphql/src/database/engine.js (hunk 3 above)
Comment (SouadHadjiat) [reply opencti-platform/opencti-graphql/src/database/engine.js:1767]: I didn't want to do too many changes here in the code, but yes elementType wording doesn't make sense

**Review by JeremyCloarec — APPROVED** [review]
