### PR TITLE
[frontend] no longer load query in EmailTemplateField in CE (#14344)

### LINKED ISSUE #14344: Creating a new user in CE edition wrongly call EE query emailTemplates
## Description

```graphql
query EmailTemplateFieldQuery(
  $orderMode: OrderingMode
  $orderBy: EmailTemplateOrdering
  $filters: FilterGroup
) {
  emailTemplates(orderMode: $orderMode, orderBy: $orderBy, filters: $filters) {
    edges {
      node {
        id
        name
      }
    }
  }
}
```

Image

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: 6.9.13
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details: prerelease CE env

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Start a CE platform
2. Create a new user
3. Look at logs or graphQL inspector

## Expected Output

No EE call should be done when platform is CE

### PR DESCRIPTION
**Pull request by JeremyCloarec**
### Proposed changes

* no longer load query in EmailTemplateField in CE
*

### Related issues

* fix #14344
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/common/form/EmailTemplateField.tsx [hunk 1]
```diff
@@ -128,6 +126,7 @@ const EmailTemplateField = ({ ...props }: EmailTemplateFieldProps) => {
     );
   }
 
+  const queryRef = useQueryLoading<EmailTemplateFieldQuery>(emailTemplateFieldQuery);
```
Comment (esrevi) [inline opencti-platform/opencti-front/src/private/components/common/form/EmailTemplateField.tsx]: actually, moving this hook breaks the react rules of hooks, it should not be called under a condition.

one solution could be splitting in two distinct components

```
const EmailTemplateFieldLoader = (props: EmailTemplateFieldProps) => {
  const queryRef = useQueryLoading<EmailTemplateFieldQuery>(emailTemplateFieldQuery);
  const { name, label } = props;

  return queryRef ? (
    <React.Suspense fallback={(
      <Field
        component={AutocompleteField}
        name={name}
        disabled={true}
        fullWidth={true}
        options={[]}
        renderOption={() => null}
        textfieldprops={{ label }}
      />
    )}>
      <EmailTemplateFieldComponent {...props} queryRef={queryRef} />
    </React.Suspense>
  ) : (
    <Loader variant={LoaderVariant.inElement} />
  );
};

const EmailTemplateField = ({ ...props }: EmailTemplateFieldProps) => {
  const { t_i18n } = useFormatter();
  const isEnterpriseEdition = useEnterpriseEdition();
  const { name } = props;

  if (!isEnterpriseEdition) {
    return (
      <EETooltip title={t_i18n('Only available in EE')}>
        <Field
          component={AutocompleteField}
          name={name}
          disabled={true}
          fullWidth={true}
          options={[]}
          style={fieldSpacingContainerStyle}
          renderOption={() => null}
          textfieldprops={{ label: t_i18n('Email template') }}
        />
      </EETooltip>
    );
  }

  return <EmailTemplateFieldLoader {...props} />;
};
```

**Review by esrevi — APPROVED** [review]
